'use strict';

/**
 * @ngdoc function
 * @name pathfinderCharacterBuilderApp.controller:SpellCtrl
 * @description
 * # SpellCtrl
 * Controller of the pathfinderCharacterBuilderApp
 */
angular.module('pathfinderCharacterBuilderApp')
  .controller('SpellCtrl', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
    this.spellsWithDescriptions = spellsWithDescriptions;
    this.spells = spells;
    this.spellsByClass = spellsByClass;
  });

var spellsWithDescriptions = [
  {
    name: "Fireball",
    school: "evocation",
    subschool: null,
    descriptor: "fire",
    spellLevel: "sorcerer/wizard 3, magus 3"
  },
  {
    name: "Cure Light Wounds",
    school: "conjuration",
    subschool: "healing",
    descriptor: null,
    spellLevel: "bard 1, cleric 1, druid 1, paladin 1, ranger 2, witch 1, inquisitor 1, alchemist 1"
  }
];

var spells = [
  "Ablative Barrier",
  "Aboleth's Lung",
  "Absorb Toxicity",
  "Absorbing Inhalation",
  "Absorbing Touch",
  "Abundant Ammunition",
  "Accelerate Poison",
  "Acid Arrow",
  "Acid Fog",
  "Acid Pit",
  "Acid Splash",
  "Acidic Spray",
  "Acute Senses",
  "Adhesive Blood",
  "Adhesive Spittle",
  "Adjuring Step",
  "Adjustable Disguise",
  "Adjustable Polymorph",
  "Adoration",
  "Age Resistance, Greater",
  "Age Resistance, Lesser",
  "Age Resistance",
  "Agressive Thundercloud",
  "Aggressive Thundercloud, Greater",
  "Agonize",
  "Agonizing Rebuke",
  "Aid",
  "Air Bubble",
  "Air Geyser",
  "Air Step",
  "Air Walk, Communal",
  "Air Walk",
  "Alarm",
  "Alchemical Allocation",
  "Alchemical Tinkering",
  "Align Weapon",
  "Align Weapon, Communal",
  "Allegro",
  "Allfood",
  "Alter Self",
  "Alter Musical Instrument",
  "Alter Winds",
  "Amplify Elixir",
  "Analyze Dweomer",
  "Ancestral Regression",
  "Anchored Step",
  "Animal Aspect, Greater",
  "Animal Aspect",
  "Animal Growth",
  "Animal Messenger",
  "Animal Purpose Training",
  "Animal Shapes",
  "Animal Trance",
  "Animate Dead, Lesser",
  "Animate Dead",
  "Animate Objects",
  "Animate Plants",
  "Animate Rope",
  "Anonymous Interaction",
  "Ant Haul",
  "Ant Haul, Communal",
  "Anthropomorphic Animal",
  "Anticipate Peril",
  "Anti-Incorporeal Shell",
  "Antilife Shell",
  "Antimagic Field",
  "Antipathy",
  "Antiplant Shell",
  "Aqueous Orb",
  "Arboreal Hammer",
  "Arcana Theft",
  "Arcane Cannon",
  "Arcane Concordance",
  "Arcane Eye",
  "Arcane Lock",
  "Arcane Mark",
  "Arcane Sight, Greater",
  "Arcane Sight",
  "Archon's Aura",
  "Arrow Eruption",
  "Arrow of Law",
  "Ash Storm",
  "Aspect of the Bear",
  "Aspect of the Falcon",
  "Aspect of the Stag",
  "Aspect of the Wolf",
  "Astral Projection, Lesser",
  "Astral Projection",
  "Atavism, Mass",
  "Atavism",
  "Atonement",
  "Augury",
  "Aura of Doom",
  "Aura of Greater Courage",
  "Aura Sight",
  "Awaken",
  "Badger's Ferocity",
  "Baleful Polymorph",
  "Ball Lightning",
  "Bane",
  "Banish Seeming",
  "Banishment",
  "Banshee Blaste",
  "Bard's Escape",
  "Barkskin",
  "Barrow Haze",
  "Battlemind Link",
  "Battle Trance",
  "Bear's Endurance, Mass",
  "Bear's Endurance",
  "Beast Shape I",
  "Beast Shape II",
  "Beast Shape III",
  "Beast Shape IV",
  "Beastspeak",
  "Beguiling Gift",
  "Bestow Auras",
  "Bestow Curse",
  "Bestow Grace of the Champion",
  "Bestow Grace",
  "Bestow Insight",
  "Bestow Weapon Proficiency",
  "Binding",
  "Binding Earth",
  "Binding Earth, Mass",
  "Black Mark",
  "Black Tentacles",
  "Blade Barrier",
  "Blade Lash",
  "Blade of Bright Victory",
  "Blade of Dark Triumph",
  "Blasphemy",
  "Blaze of Glory",
  "Blazing Rainbow",
  "Bleed",
  "Blend",
  "Bless Water",
  "Bless Weapon",
  "Bless",
  "Blessed Fist",
  "Blessing of Courage and Life",
  "Blessing of Fervor",
  "Blessing of Luck and Resolve",
  "Blessing of Luck and Resolve, Mass",
  "Blessing of the Mole",
  "Blessing of the Salamander",
  "Blight",
  "Blinding Ray",
  "Blindness Deafness",
  "Blink",
  "Blistering Invective",
  "Bloatbomb",
  "Blood Armor",
  "Blood Biography",
  "Blood Blaze",
  "Blood Crow Strike",
  "Blood Mist",
  "Blood Transcription",
  "Blood Scent",
  "Blood Sentinel",
  "Bloodhound",
  "Bloody Claws",
  "Blur",
  "Blurred Movement",
  "Body Capacitance",
  "Boiling Blood",
  "Bomber's Eye",
  "Borrow Fortune",
  "Borrow Skill",
  "Bow Spirit",
  "Bowstaff",
  "Brand, Greater",
  "Brand",
  "Break",
  "Break Enchantment",
  "Breath of Life",
  "Brilliant Inspiration",
  "Bristle",
  "Brow Gasher",
  "Bull's Strength, Mass",
  "Bull's Strength",
  "Bullet Shield",
  "Bullet Ward",
  "Bungle",
  "Buoyancy",
  "Burning Gaze",
  "Burning Hands",
  "Burrow",
  "Burst Bonds",
  "Burst of Nettles",
  "Burst of Speed",
  "Cackling Skull",
  "Cacophonous Call, Mass",
  "Cacophonous Call",
  "Caging Bomb Admixture",
  "Calcific Touch",
  "Call Animal",
  "Call Construct",
  "Call Lightning Storm",
  "Call Lightning",
  "Calm Animals",
  "Calm Emotions",
  "Campfire Wall",
  "Cape of Wasps",
  "Cast Out",
  "Castigate, Mass",
  "Castigate",
  "Cat's Grace, Mass",
  "Cat's Grace",
  "Cause Fear",
  "Caustic Eruption",
  "Certain Grip",
  "Chains of Fire",
  "Chain Lightning",
  "Chain of Perdition",
  "Challenge Evil",
  "Chameleon Stride",
  "Chameleon Stride, Greater",
  "Changestaff",
  "Chaos Hammer",
  "Charm Animal",
  "Charm Monster, Mass",
  "Charm Monster",
  "Charm Person",
  "Chill Metal",
  "Chill Touch",
  "Chord of Shards",
  "Circle of Clarity",
  "Circle of Death",
  "Clairaudience Clairvoyance",
  "Clashing Rocks",
  "Cleanse",
  "Clenched Fist",
  "Climbing Beanstalk",
  "Cloak of Chaos",
  "Cloak of Dreams",
  "Cloak of Shade",
  "Cloak of Winds",
  "Clone",
  "Cloudkill",
  "Cloud Shape",
  "Cold Ice Strike",
  "Color Spray",
  "Command, Greater",
  "Command Plants",
  "Command Undead",
  "Command",
  "Commune with Birds",
  "Commune with Nature",
  "Commune",
  "Companion Life Link",
  "Companion Mind Link",
  "Compassionate Ally",
  "Compel Hostility",
  "Comprehend Languages",
  "Cone of Cold",
  "Confess",
  "Confusion Lesser",
  "Confusion",
  "Conjure Black Pudding",
  "Consecrate",
  "Contact Other Plane",
  "Contagion, Greater",
  "Contagion",
  "Contagious Flame",
  "Contingency",
  "Contingent Action",
  "Contingent Scroll",
  "Continual Flame",
  "Control Construct",
  "Control Plants",
  "Control Summoned Creature",
  "Control Undead",
  "Control Water",
  "Control Weather",
  "Control Winds",
  "Coordinated Effort",
  "Corrosive Consumption",
  "Corrosive Touch",
  "Corruption Resistance",
  "Countless Eyes",
  "Coward's Lament",
  "Crafter's Curse",
  "Crafter's Fortune",
  "Create Demiplane, Greater",
  "Create Demiplane, Lesser",
  "Create Demiplane",
  "Create Food and Water",
  "Create Greater Undead",
  "Create Pit",
  "Create Treasure Map",
  "Create Undead",
  "Create Water",
  "Creeping Doom",
  "Creeping Ice",
  "Crimson Confession",
  "Crushing Despair",
  "Crushing Hand",
  "Cup of Dust",
  "Cure Critical Wounds, Mass",
  "Cure Critical Wounds",
  "Cure Light Wounds, Mass",
  "Cure Light Wounds",
  "Cure Moderate Wounds, Mass",
  "Cure Moderate Wounds",
  "Cure Serious Wounds, Mass",
  "Cure Serious Wounds",
  "Curse of Burning Sleep",
  "Curse of Disgust",
  "Curse of Magic Negation",
  "Curse Water",
  "Curse, Major",
  "Cursed Earth",
  "Cushioning Bands",
  "Damnation Stride",
  "Damp Powder",
  "Dance of A Hundred Cuts",
  "Dance of A Thousand Cuts",
  "Dancing Lantern",
  "Dancing Lights",
  "Darkness",
  "Darkvision, Communal",
  "Darkvision, Greater",
  "Darkvision",
  "Daybreak Arrow",
  "Daylight",
  "Daze Monster",
  "Daze, Mass",
  "Daze",
  "Deadeye's Lore",
  "Deadly Finale",
  "Deadly Juggernaut",
  "Deafening Song Bolt",
  "Death Candle",
  "Death from Below",
  "Death Knell",
  "Death Ward",
  "Deathwatch",
  "Debilitating Portent",
  "Decompose Corpse",
  "Deep Slumber",
  "Deeper Darkness",
  "Defensive Shock",
  "Defile Armor",
  "Deflection",
  "Delay Disease",
  "Delay Pain",
  "Delay Poison, Communal",
  "Delay Poison",
  "Delayed Blast Fireball",
  "Delayed Consumption",
  "Delusional Pride",
  "Demand",
  "Denounce",
  "Desecrate",
  "Destabilize Powder",
  "Destruction",
  "Detect Aberration",
  "Detect Animals or Plants",
  "Detect Chaos",
  "Detect Evil",
  "Detect Good",
  "Detect Law",
  "Detect Magic",
  "Detect Magic",
  "Detect Poison",
  "Detect Scrying",
  "Detect Secret Doors",
  "Detect Snares and Pits",
  "Detect Thoughts",
  "Detect Undead",
  "Detonate",
  "Devolution",
  "Diagnose Disease",
  "Dictum",
  "Dimension Door",
  "Dimensional Anchor",
  "Dimensional Lock",
  "Dimensional",
  "Dimensional Bounce",
  "Diminish Plants",
  "Disable Construct",
  "Discern Lies",
  "Discern Location",
  "Discern Next of Kin",
  "Discordant Blast",
  "Discovery Torch",
  "Disfiguring Touch",
  "Disguise Other",
  "Disguise Self",
  "Disguise Weapon",
  "Disintegrate",
  "Dismissal",
  "Dispel Chaos",
  "Dispel Evil",
  "Dispel Good",
  "Dispel Law",
  "Dispel Magic, Greater",
  "Dispel Magic",
  "Displacement",
  "Disrupt Undead",
  "Disrupting Weapon",
  "Distracting Cacophony",
  "Distressing Tone",
  "Divination",
  "Divine Arrow",
  "Divine Favor",
  "Divine Power",
  "Divine Pursuit",
  "Divine Transfer",
  "Divine Vessel",
  "Dominate Animal",
  "Dominate Monster",
  "Dominate Person",
  "Doom",
  "Draconic Reservoir",
  "Dragon's Breath",
  "Dread Bolt",
  "Dream",
  "Dust Form",
  "Dust of Twilight",
  "Eagle Aerie",
  "Eagle Eye",
  "Eagle's Splendor, Mass",
  "Eagle's Splendor",
  "Ear Piercing Scream",
  "Earth Glide",
  "Earthquake",
  "Echolocation",
  "Effortless Armor",
  "Eldritch Fever",
  "Elemental Aura",
  "Elemental Body I",
  "Elemental Body II",
  "Elemental Body III",
  "Elemental Body IV",
  "Elemental Speech",
  "Elemental Swarm",
  "Elemental Touch",
  "Elude Time",
  "Enchantment Foil",
  "Endure Elements, Communal",
  "Endure Elements",
  "Enemy Hammer",
  "Enemy's Heart",
  "Enemy Insight",
  "Energy Drain",
  "Energy Siege Shot, Greater",
  "Energy Siege Shot",
  "Enervation",
  "Enlarge Person, Mass",
  "Enlarge Person",
  "Entangle",
  "Enter Image",
  "Enthrall",
  "Entropic Shield",
  "Envious Urge",
  "Epidemic",
  "Erase",
  "Eruptive Pustules",
  "Escaping Ward",
  "Ethereal Jaunt",
  "Etherealness",
  "Euphoric Cloud",
  "Euphoric Tranquility",
  "Evolution Surge, Greater",
  "Evolution Surge, Lesser",
  "Evolution Surge",
  "Excruciating Deformation",
  "Expeditious Excavation",
  "Expeditious Retreat",
  "Expend",
  "Explosive Runes",
  "Extreme Flexibility",
  "Exquisite Accompaniment",
  "Eyebite",
  "Eyes of the Void",
  "Fabricate Bullets",
  "Fabricate",
  "Faerie Fire",
  "Fairy Ring Retreat",
  "False Life, Greater",
  "False Life",
  "False Vision",
  "Familiar Double",
  "Familiar Melding",
  "Fear",
  "Fearsome Duplicate",
  "Feast of Ashes",
  "Feast on Fear",
  "Feather Fall",
  "Feather Step, Mass",
  "Feather Step",
  "Feeblemind",
  "Fester, Mass",
  "Fester",
  "Fickle Winds",
  "Fiery Body",
  "Fiery Shuriken",
  "Find Quarry",
  "Find the Path",
  "Find Traps",
  "Finger of Death",
  "Fins to Feet",
  "Fire Breath",
  "Fire of Entanglement",
  "Fire of Judgment",
  "Fire of Vengeance",
  "Fire Seeds",
  "Fire Shield",
  "Fire Snake",
  "Fire Storm",
  "Firestream",
  "Fire Trail",
  "Fire Trap",
  "Fireball",
  "Firebrand",
  "Firefall",
  "Flame Arrow",
  "Flame Blade",
  "Flame Strike",
  "Flames of the Faithful",
  "Flaming Sphere",
  "Flaming Sphere, Greater",
  "Flare Burst",
  "Flare",
  "Flash Fire",
  "Flesh to Stone",
  "Fleshworm Infestation",
  "Flexible Fury",
  "Floating Disk",
  "Fluid Form",
  "Fly, Mass",
  "Fly",
  "Focused Scrutiny",
  "Foe to Friend",
  "Fog Cloud",
  "Follow Aura",
  "Font of Spirit Magic",
  "Fool's Forbiddance",
  "Forbid Action, Greater",
  "Forbid Action",
  "Forbiddance",
  "Force Hook Charge",
  "Force Punch",
  "Forcecage",
  "Forced Quiet",
  "Forced Repentance",
  "Forceful Hand",
  "Forgetful Slumber",
  "Foresight",
  "Forest Friend",
  "Form of the Dragon I",
  "Form of the Dragon II",
  "Form of the Dragon III",
  "Fox's Cunning, Mass",
  "Fox's Cunning",
  "Freedom of Movement",
  "Freedom",
  "Freezing Sphere",
  "Frightful Aspect",
  "Frigid Touch",
  "Frost Fall",
  "Frostbite",
  "Frozen Note",
  "Fumbletongue",
  "Fungal Infestation",
  "Fury of the Sun",
  "Gallant Inspiration",
  "Gaseous Form",
  "Gate",
  "Geas Lesser",
  "Geas Quest",
  "Gentle Breeze",
  "Gentle Repose",
  "Getaway",
  "Geyser",
  "Ghost Sound",
  "Ghostbane Dirge, Mass",
  "Ghostbane Dirge",
  "Ghostly Disguise",
  "Ghoul Touch",
  "Giant Form I",
  "Giant Form II",
  "Giant Vermin",
  "Ghost Wolf",
  "Glibness",
  "Glide",
  "Glitterdust",
  "Globe of Invulnerability Lesser",
  "Globe of Invulnerability",
  "Gloomblind Bolts",
  "Glue Seal",
  "Glyph of Warding, Greater",
  "Glyph of Warding",
  "Good Hope",
  "Goodberry",
  "Grace",
  "Grasping Hand",
  "Gravity Bow",
  "Grease",
  "Greater Command",
  "Grove of Respite",
  "Guards and Wards",
  "Groundswell",
  "Guardian of Faith",
  "Guidance",
  "Guiding Star",
  "Gust of Wind",
  "Gusting Sphere",
  "Half-blood Extraction",
  "Hallow",
  "Hallucinatory Terrain",
  "Halt Undead",
  "Harm",
  "Haste",
  "Haunted Fey Aspect",
  "Haunting Choir",
  "Haunting Mists",
  "Heal, Mass",
  "Heal Mount",
  "Heal",
  "Healing Thief",
  "Healing Warmth",
  "Heart of the Metal",
  "Heat Metal",
  "Heightened Awareness",
  "Heightened Reflexes",
  "Helping Hand",
  "Hellmouth Lash",
  "Hero's Defiance",
  "Heroes Feast",
  "Heroic Finale",
  "Heroic Invocation",
  "Heroism, Greater",
  "Heroism",
  "Hex Glyph",
  "Hex Glyph, Greater",
  "Hex Vulnerability",
  "Hex Ward",
  "Hidden Speech",
  "Hide Campsite",
  "Hide from Animals",
  "Hide from Undead",
  "Hideous Laughter",
  "Hold Animal",
  "Hold Monster, Mass",
  "Hold Monster",
  "Hold Person, Mass",
  "Hold Person",
  "Hold Portal",
  "Holy Aura",
  "Holy Ice",
  "Holy Ice Weapon",
  "Holy Shield",
  "Holy Smite",
  "Holy Sword",
  "Holy Whisper",
  "Holy Word",
  "Honeyed Tongue",
  "Horn of Pursuit",
  "Horrid Wilting",
  "Hostile Juxtaposition, Greater",
  "Hostile Juxtaposition",
  "Hostile Levitation",
  "Howling Agony",
  "Hungry Pit",
  "Hunter's Eye",
  "Hunter's Howl",
  "Hydraulic Push",
  "Hydraulic Torrent",
  "Hypnotic Pattern",
  "Hypnotism",
  "Ice Body",
  "Ice Crystal Teleport",
  "Ice Storm",
  "Icicle Dagger",
  "Icy Prison, Mass",
  "Icy Prison",
  "Identify",
  "Ill Omen",
  "Illusion of Calm",
  "Illusory Script",
  "Illusory Wall",
  "Imbue with Aura",
  "Imbue with Elemental Might",
  "Imbue with Spell Ability",
  "Implosion",
  "Imprisonment",
  "Improve Trap",
  "Incendiary Cloud",
  "Inflict Critical Wounds, Mass",
  "Inflict Critical Wounds",
  "Inflict Light Wounds, Mass",
  "Inflict Light Wounds",
  "Inflict Moderate Wounds, Mass",
  "Inflict Moderate Wounds",
  "Inflict Serious Wounds, Mass",
  "Inflict Serious Wounds",
  "Innocence",
  "Insanity",
  "Insect Plague",
  "Instant Armor",
  "Instant Enemy",
  "Instant Summons",
  "Instrument of Agony",
  "Interplanetary Teleport",
  "Interposing Hand",
  "Interrogation, Greater",
  "Interrogation",
  "Investigate Mind",
  "Invigorate, Mass",
  "Invigorate",
  "Invisibility Alarm",
  "Invisibility, Greater",
  "Invisibility, Mass",
  "Invisibility Purge",
  "Invisibility Sphere",
  "Invisibility",
  "Ironbeard",
  "Iron Body",
  "Ironwood",
  "Irresistible Dance",
  "Jester's Jaunt",
  "Jitterbugs",
  "Jolting Portent",
  "Joyful Rapture",
  "Judgment Light",
  "Jump",
  "Jury Rig",
  "Karmic Blessing",
  "Keen Edge",
  "Keen Senses",
  "Ki Arrow",
  "Ki Leech",
  "Ki Shout",
  "Kinetic Reverberation",
  "King's Castle",
  "Knight's Calling",
  "Knock",
  "Know Direction",
  "Know the Enemy",
  "Languid Bomb Admixture",
  "Lead Blades",
  "Leashed Shackles",
  "Legend Lore",
  "Lend Judgment, Greater",
  "Lend Judgment",
  "Lesser Restoration",
  "Levitate",
  "Liberating Command",
  "Life Bubble",
  "Life Channel",
  "Life Conduit, Greater",
  "Life Conduit, Improved",
  "Life Conduit",
  "Light Lance",
  "Life Pact",
  "Light",
  "Lightning Arc",
  "Lightning Bolt",
  "Lightning Lash Bomb Admixture",
  "Lily Pad Stride",
  "Limited Wish",
  "Linebreaker",
  "Line in the Sand",
  "Litany of Defense",
  "Litany of Eloquence",
  "Litany of Entanglement",
  "Litany of Escape",
  "Litany of Madness",
  "Litany of Righteousness",
  "Litany of Sight",
  "Litany of Sloth",
  "Litany of Thunder",
  "Litany of Vengeance",
  "Litany of Warding",
  "Litany of Weakness",
  "Liveoak",
  "Loathsome Veil",
  "Locate Creature",
  "Locate Object",
  "Locate Weakness",
  "Lock Gaze",
  "Lockjaw",
  "Long Arm",
  "Longshot",
  "Longstrider",
  "Longstrider, Greater",
  "Lullaby",
  "Lunar Veil",
  "Mad Hallucination",
  "Mad Monkeys",
  "Mage Armor",
  "Mage Hand",
  "Mage's Disjunction",
  "Mage's Faithful Hound",
  "Mage's Lucubration",
  "Mage's Magnificent Mansion",
  "Mage's Private Sanctum",
  "Mage's Sword",
  "Magic Aura",
  "Magic Circle Against Chaos",
  "Magic Circle Against Evil",
  "Magic Circle Against Good",
  "Magic Circle Against Law",
  "Magic Fang, Greater",
  "Magic Fang",
  "Magic Jar",
  "Magic Missile",
  "Magic Mouth",
  "Magic Siege Engine, Greater",
  "Magic Siege Engine",
  "Magic Stone",
  "Magic Vestment",
  "Magic Weapon, Greater",
  "Magic Weapon",
  "Magnifying Chime",
  "Major Creation",
  "Major Image",
  "Major Phantom Object",
  "Make Whole",
  "Malfunction",
  "Malicious Spite",
  "Mantle of Calm",
  "Marching Chant",
  "Marid's Mastery",
  "Marionette Possession",
  "Mark of Justice",
  "Mark of Obvious Ethics",
  "Marks of Forbiddance",
  "Mask Dweomer, Communal",
  "Mask Dweomer",
  "Masterwork Transformation",
  "Maze",
  "Meld Into Stone",
  "Memory Lapse",
  "Memorize Page",
  "Mending",
  "Message",
  "Meteor Swarm",
  "Miasmatic Form",
  "Mighty Fist of the Earth",
  "Mind Blank, Communal",
  "Mind Blank",
  "Mind Fog",
  "Mindlocked Messenger",
  "Minor Creation",
  "Minor Dream",
  "Minor Image",
  "Minor Phantom Object",
  "Miracle",
  "Mirage Arcana",
  "Mirror Hideaway",
  "Mirror Image",
  "Mirror Polish",
  "Mirror Strike",
  "Mirror Transport",
  "Misdirection",
  "Miserable Pity",
  "Mislead",
  "Mnemonic Enhancer",
  "Modify Memory",
  "Molten Orb",
  "Moment of Greatness",
  "Moment of Prescience",
  "Monkey Fish",
  "Monstrous Physique I",
  "Monstrous Physique II",
  "Monstrous Physique III",
  "Monstrous Physique IV",
  "Moonstruck",
  "Mount, Communal",
  "Mount",
  "Move Earth",
  "Muffle Sound",
  "Murderous Command",
  "Mutagenic Touch",
  "Named Bullet, Greater",
  "Named Bullet",
  "Nap Stack",
  "Natural Rhythm",
  "Nature's Exile",
  "Nauseating Dart",
  "Nauseating Trail",
  "Negate Aroma",
  "Negative Reaction",
  "Nereid's Grace",
  "Neutralize Poison",
  "Nightmare",
  "Nine Lives",
  "Nixie's Lure",
  "Nondetection, Communal",
  "Nondetection",
  "Oath of Peace",
  "Obscure Object",
  "Obscuring Mist",
  "Obsidian Flow",
  "Old Salt's Curse",
  "Open Close",
  "Oppressive Boredom",
  "Oracle's Burden",
  "Oracle's Vessel",
  "Orb of the Void",
  "Order's Wrath",
  "Overland Flight",
  "Overwhelming Grief",
  "Overwhelming Presence",
  "Owl's Wisdom, Mass",
  "Owl's Wisdom",
  "Pain Strike, Mass",
  "Pain Strike",
  "Paladin's Sacrifice",
  "Paragon Surge",
  "Pass Without Trace",
  "Passwall",
  "Path of Glory",
  "Path of Glory, Greater",
  "Path of the Winds",
  "Peacebond",
  "Pellet Blast",
  "Perceive Cues",
  "Permanency",
  "Permanent Image",
  "Pernicious Poison",
  "Persistent Image",
  "Persistent Vigor",
  "Persuasive Goad",
  "Phantasmal Killer",
  "Phantasmal Revenge",
  "Phantasmal Web",
  "Phantom Blood",
  "Phantom Chariot",
  "Phantom Driver",
  "Phantom Steed, Communal",
  "Phantom Steed",
  "Phantom Trap",
  "Phase Door",
  "Pied Piping",
  "Pierce Disguise",
  "Piercing Shriek",
  "Pilfering Hand",
  "Pillar of Life",
  "Plague Carrier",
  "Plague Storm",
  "Planar Adaptation, Mass",
  "Planar Adaptation",
  "Planar Ally, Greater",
  "Planar Ally Lesser",
  "Planar Ally",
  "Planar Binding, Greater",
  "Planar Binding Lesser",
  "Planar Binding",
  "Plane Shift",
  "Planeslayer's Call",
  "Plant Growth",
  "Plant Shape I",
  "Plant Shape II",
  "Plant Shape III",
  "Play Instrument",
  "Poison",
  "Polar Midnight",
  "Polar Ray",
  "Polymorph Any Object",
  "Polymorph Familiar",
  "Polymorph, Greater",
  "Polymorph",
  "Polypurpose Panacea",
  "Possess Object",
  "Power Word Blind",
  "Power Word Kill",
  "Power Word Stun",
  "Pox Pustules",
  "Prayer",
  "Prediction of Failure",
  "Prehensile Pilfer",
  "Prestidigitation",
  "Primal Scream",
  "Prismatic Sphere",
  "Prismatic Spray",
  "Prismatic Wall",
  "Produce Flame",
  "Programmed Image",
  "Project Image",
  "Protection from Arrows, Communal",
  "Protection from Arrows",
  "Protection from Chaos, Communal",
  "Protection from Chaos",
  "Protection from Energy, Communal",
  "Protection from Energy",
  "Protection from Evil, Communal",
  "Protection from Evil",
  "Protection from Good, Communal",
  "Protection from Good",
  "Protection from Law, Communal",
  "Protection from Law",
  "Protection from Spells",
  "Protective Penumbra",
  "Protective Spirit",
  "Prying Eyes, Greater",
  "Prying Eyes",
  "Pup Shape",
  "Purging Finale",
  "Purified Calling",
  "Purify Food and Drink",
  "Putrefy Food and Drink",
  "Pyrotechnics",
  "Qualm",
  "Quench",
  "Raging Rubble",
  "Rage",
  "Rain of Frogs",
  "Rainbow Pattern",
  "Raise Animal Companion",
  "Raise Dead",
  "Rally Point",
  "Rampart",
  "Rapid Repair",
  "Ray of Enfeeblement",
  "Ray of Exhaustion",
  "Ray of Frost",
  "Ray of Sickening",
  "Read Magic",
  "Rebuke",
  "Recharge Innate Magic",
  "Reckless Infatuation",
  "Recoil Fire",
  "Reduce Animal",
  "Reduce Person, Mass",
  "Reduce Person",
  "Refine Improvised Weapon",
  "Refuge",
  "Regenerate",
  "Reincarnate",
  "Reinforce Armaments, Communal",
  "Reinforce Armaments",
  "Rejuvenate Eidolon, Greater",
  "Rejuvenate Eidolon, Lesser",
  "Rejuvenate Eidolon",
  "Reloading Hands",
  "Remove Blindness Deafness",
  "Remove Curse",
  "Remove Disease",
  "Remove Fear",
  "Remove Paralysis",
  "Remove Sickness",
  "Repair Undead",
  "Repair Undead, Mass",
  "Repel Metal or Stone",
  "Repel Vermin",
  "Repel Wood",
  "Reprobation",
  "Repulsion",
  "Residual Tracking",
  "Resilient Reservoir",
  "Resilient Sphere",
  "Resinous Skin",
  "Resist Energy, Communal",
  "Resist Energy",
  "Resistance",
  "Resonating Word",
  "Resounding Blow",
  "Rest Eternal",
  "Restful Sleep",
  "Restoration, Greater",
  "Restoration Lesser",
  "Restoration",
  "Restore Corpse",
  "Restore Eidolon, Lesser",
  "Restore Eidolon",
  "Resurgent Transformation",
  "Resurrection",
  "Retribution",
  "Returning Weapon, Communal",
  "Returning Weapon",
  "Reverse Gravity",
  "Reviving Finale",
  "Ricochet Shot",
  "Ride the Lightning",
  "Ride the Waves",
  "Righteous Might",
  "Righteous Vigor",
  "River of Wind",
  "River Whip",
  "Rope Trick",
  "Rusting Grasp",
  "Sacred Bond",
  "Sacred Space",
  "Sacrificial Oath",
  "Saddle Surge",
  "Sanctify Armor",
  "Sanctify Corpse",
  "Sanctuary",
  "Sands of Time",
  "Savage Maw",
  "Saving Finale",
  "Scare",
  "Scent Trail",
  "Scintillating Pattern",
  "Scorching Ash Form",
  "Scorching Ray",
  "Scouring Winds",
  "Screech",
  "Screen",
  "Scrying, Greater",
  "Scrying",
  "Sculpt Corpse",
  "Sculpt Simulacrum",
  "Sculpt Sound",
  "Seamantle",
  "Searing Light",
  "Secret Chest",
  "Secret Page",
  "Secure Shelter",
  "See Alignment",
  "See Invisibility",
  "Seek Thoughts",
  "Seeming",
  "Sending",
  "Sense Spirit Magic",
  "Sentry Skull",
  "Sepia Snake Sigil",
  "Sequester",
  "Serenity",
  "Shades",
  "Shadow Bomb Admixture",
  "Shadow Conjuration, Greater",
  "Shadow Conjuration",
  "Shadow Evocation, Greater",
  "Shadow Evocation",
  "Shadow Projection",
  "Shadow Step",
  "Shadow Walk",
  "Shadow Weapon",
  "Shadowbard",
  "Shadow Anchor",
  "Shadowy Haven",
  "Shambler",
  "Shapechange",
  "Shard of Chaos",
  "Share Language",
  "Share Language, Communal",
  "Share Memory",
  "Share Senses",
  "Shared Wrath",
  "Shatter",
  "Shield Companion",
  "Shield of Faith",
  "Shield of Fortification",
  "Shield of Law",
  "Shield Other",
  "Shield",
  "Shifting Sand",
  "Shillelagh",
  "Shock Shield",
  "Shocking Grasp",
  "Shocking Image",
  "Shout, Greater",
  "Shout",
  "Shrink Item",
  "Siege of Trees, Greater",
  "Siege of Trees",
  "Sickening Entanglement",
  "Sickening Strikes",
  "Sift",
  "Silence",
  "Silent Image",
  "Silent Table",
  "Silk to Steel",
  "Silver Darts",
  "Simulacrum, Lesser",
  "Simulacrum",
  "Sirocco",
  "Skinsend",
  "Slay Living",
  "Sleep",
  "Sleepwalk",
  "Sleet Storm",
  "Slipstream",
  "Slow",
  "Slowing Mud",
  "Smug Narcissism",
  "Snake Staff",
  "Snapdragon Fireworks",
  "Snare",
  "Soften Earth and Stone",
  "Solid Fog",
  "Solid Note",
  "Song of Discord",
  "Sonic Form",
  "Sonic Scream",
  "Sonic Thrust",
  "Soothe Construct",
  "Soul Bind",
  "Sound Burst",
  "Sow Thought",
  "Spark",
  "Spawn Ward",
  "Speak with Animals",
  "Speak with Dead",
  "Speak with Haunt",
  "Speak with Plants",
  "Spear of Purity",
  "Spectral Hand",
  "Spellcrash",
  "Spellcrash, Lesser",
  "Spell Immunity, Greater",
  "Spell Immunity, Communal",
  "Spell Immunity, Greater Communal",
  "Spell Immunity",
  "Spell Resistance",
  "Spell Turning",
  "Spellstaff",
  "Spider Climb, Communal",
  "Spider Climb",
  "Spike Growth",
  "Spike Stones",
  "Spiked Pit",
  "Spiritual Ally",
  "Spiritual Weapon",
  "Spit Venom",
  "Spite",
  "Spontaneous Immolation",
  "Squeeze",
  "Stabilize Powder",
  "Stabilize",
  "Statue",
  "Status",
  "Stay the Hand",
  "Steal Breath",
  "Steal Voice",
  "Stench of Prey",
  "Stinking Cloud",
  "Stone Call",
  "Stone Discus",
  "Stone Fist",
  "Stone Shape",
  "Stone Shield",
  "Stone Tell",
  "Stone to Flesh",
  "Stoneskin, Communal",
  "Stoneskin",
  "Storm of Vengeance",
  "Stormbolts",
  "Strangling Hair",
  "Stricken Heart",
  "Strong Jaw",
  "Strong Wings",
  "Stumble Gap",
  "Stunning Barrier",
  "Stunning Barrier, Greater",
  "Stunning Finale",
  "Suffocation, Mass",
  "Suffocation",
  "Suggestion, Mass",
  "Suggestion",
  "Summon Eidolon",
  "Summon Elder Worm",
  "Summon Froghemoth",
  "Summon Instrument",
  "Summon Minor Ally",
  "Summon Minor Monster",
  "Summon Monster I",
  "Summon Monster II",
  "Summon Monster III",
  "Summon Monster IV",
  "Summon Monster IX",
  "Summon Monster Table",
  "Summon Monster V",
  "Summon Monster VI",
  "Summon Monster VII",
  "Summon Monster VIII",
  "Summon Nature's Ally I",
  "Summon Nature's Ally II",
  "Summon Nature's Ally III",
  "Summon Nature's Ally IV",
  "Summon Nature's Ally IX",
  "Summon Nature's Ally V",
  "Summon Nature's Ally VI",
  "Summon Nature's Ally VII",
  "Summon Nature's Ally VIII",
  "Summon Nature's Ally Table",
  "Summon Swarm",
  "Summoner Conduit",
  "Sun Metal",
  "Sunbeam",
  "Sunburst",
  "Sunder Breaker",
  "Sundering Shards",
  "Surmount Affliction",
  "Swarm Skin",
  "Symbol of Death",
  "Symbol of Fear",
  "Symbol of Healing",
  "Symbol of Insanity",
  "Symbol of Laughter",
  "Symbol of Mirroring",
  "Symbol of Pain",
  "Symbol of Persuasion",
  "Symbol of Revelation",
  "Symbol of Scrying",
  "Symbol of Sealing",
  "Symbol of Sleep",
  "Symbol of Slowing",
  "Symbol of Strife",
  "Symbol of Striking",
  "Symbol of Stunning",
  "Symbol of Vulnerability",
  "Symbol of Weakness",
  "Sympathetic Vibration",
  "Sympathy",
  "Tactical Acumen",
  "Tar Ball",
  "Tar Pool",
  "Targeted Bomb Admixture",
  "Telekinesis",
  "Telekinetic Assembly",
  "Telekinetic Charge",
  "Telekinetic Sphere",
  "Telepathic Bond",
  "Teleport, Greater",
  "Teleport Object",
  "Teleport",
  "Teleportation Circle",
  "Temporal Stasis",
  "Temporary Resurrection",
  "Terrain Bond",
  "Terrible Remorse",
  "Theft Ward",
  "Thorn Body",
  "Thorn Javelin",
  "Thorny Entanglement",
  "Threefold Aspect",
  "Thunder Fire",
  "Thundering Drums",
  "Thunderstomp",
  "Thunderstomp, Greater",
  "Time Shudder",
  "Time Stop",
  "Timely Inspiration",
  "Tiny Hut",
  "Tireless Pursuers",
  "Tireless Pursuit",
  "Toilsome Chant",
  "Tongues, Communal",
  "Tongues",
  "Touch Injection",
  "Touch of Combustion",
  "Touch of Fatigue",
  "Touch of Gracelessness",
  "Touch of Idiocy",
  "Touch of Slime",
  "Touch of the Sea",
  "Toxic Gift",
  "Transformation",
  "Transmogrify",
  "Transmute Blood to Acid",
  "Transmute Metal to Wood",
  "Transmute Mud to Rock",
  "Transmute Potion to Poison",
  "Transmute Rock to Mud",
  "Transport Via Plants",
  "Trap the Soul",
  "Treasure Stitching",
  "Tree Shape",
  "Tree Stride",
  "Triggered Suggestion",
  "True Form",
  "True Resurrection",
  "True Seeing",
  "Truespeak",
  "True Strike",
  "Tsunami",
  "Twilight Haze",
  "Twilight Knife",
  "Twin Form",
  "Twisted Space",
  "Unadulterated Loathing",
  "Unbearable Brightness",
  "Unbreakable Construct",
  "Undead Anatomy I",
  "Undead Anatomy II",
  "Undead Anatomy III",
  "Undead Anatomy IV",
  "Undeath to Death",
  "Undine's Curse",
  "Undetectable Alignment",
  "Unerring Weapon",
  "Unfetter",
  "Unhallow",
  "Unholy Aura",
  "Unholy Blight",
  "Unholy Ice",
  "Unholy Ice Weapon",
  "Unholy Sword",
  "Universal Formula",
  "Unliving Rage",
  "Unnatural Lust",
  "Unprepared Combatant",
  "Unseen Servant",
  "Unshakable Chill",
  "Unwilling Shield",
  "Unwitting Ally",
  "Urban Grace",
  "Utter Contempt",
  "Vampiric Shadow Shield",
  "Vampiric Touch",
  "Vanish",
  "Veil of Heaven",
  "Veil of Positive Energy",
  "Veil",
  "Vengeful Outrage",
  "Venomous Bolt",
  "Ventriloquism",
  "Vermin Shape I",
  "Vermin Shape II",
  "Versatile Weapon",
  "Vestment of the Champion",
  "Village Veil",
  "Viper Bomb Admixture",
  "Virtue",
  "Virtuoso Performance",
  "Vision of Hell",
  "Vision",
  "Vitriolic Mist",
  "Vocal Alteration",
  "Volcanic Storm",
  "Vomit Swarm",
  "Vomit Twin",
  "Vortex",
  "Wail of the Banshee",
  "Wake of Light",
  "Walk Through Space",
  "Wall of Blindness/Deafness",
  "Wall of Fire",
  "Wall of Force",
  "Wall of Ice",
  "Wall of Iron",
  "Wall of Lava",
  "Wall of Nausea",
  "Wall of Sound",
  "Wall of Stone",
  "Wall of Suppression",
  "Wall of Thorns",
  "Wandering Star Motes",
  "Ward the Faithful",
  "Ward of the Season",
  "Warding Weapon",
  "Warp Wood",
  "Wartrain Mount",
  "Water Breathing",
  "Water Walk, Communal",
  "Water Walk",
  "Wave Shield",
  "Waves of Ecstasy",
  "Waves of Exhaustion",
  "Waves of Fatigue",
  "Weaken Powder",
  "Weapon of Awe",
  "Web Shelter",
  "Web",
  "Web Bolt",
  "Web Cloud",
  "Weird",
  "Whip of Ants",
  "Whip of Centipedes",
  "Whip of Spiders",
  "Whirlwind",
  "Whispering Lore",
  "Whispering Wind",
  "Widen Auras",
  "Wilderness Soldiers",
  "Wind Walk",
  "Wind Wall",
  "Winds of Vengeance",
  "Wind Blades",
  "Windy Escape",
  "Winter Feathers",
  "Wish",
  "Witness",
  "Wood Shape",
  "Wooden Phalanx",
  "Word of Chaos",
  "Word of Recall",
  "Word of Resolve",
  "World Wave",
  "Wrath",
  "Wrathful Mantle",
  "Wreath of Blades",
  "Youthful Appearance",
  "Zone of Silence",
  "Zone of Truth"
];

var spellsByClass = {
  /* =============== */
  /* Table: Bard     */
  /* =============== */
  bard: {
    0: [
    "Dancing Lights: Creates torches or other lights.",
    "Daze: Humanoid creature of 4 HD or less loses next action.",
    "Detect Magic: Detects spells and magic items within 60 ft.",
    "Flare: Dazzles one creature (–1 on attack rolls).",
    "Ghost Sound: Figment sounds.",
    "Know Direction: You discern north.",
    "Light: Object shines like a torch.",
    "Lullaby: Makes subject drowsy: –5 on Perception checks, –2 on Will saves against sleep.",
    "Mage Hand: 5-pound telekinesis.",
    "Mending: Makes minor repairs on an object.",
    "Message: Whisper conversation at distance.",
    "Open/Close: Opens or closes small or light things.",
    "Prestidigitation: Performs minor tricks.",
    "Read Magic: Read scrolls and spellbooks.",
    "Resistance: Subject gains +1 on saving throws.",
    "Summon Instrument: Summons one musical instrument.",
    ],
    1: [
    "Alarm: Wards an area for 2 hours/level.",
    "Animate Rope: Makes a rope move at your command.",
    "Cause Fear: One creature of 5 HD or less flees for 1d4 rounds.",
    "Charm Person: Makes one person your friend.",
    "Comprehend Languages: You understand all languages.",
    "Confusion, Lesser: One creature is confused for 1 round.",
    "Cure Light Wounds: Cures 1d8 damage + 1/level (max +5).",
    "Detect Secret Doors: Reveals hidden doors within 60 ft.",
    "Disguise Self: Changes your appearance.",
    "Erase: Mundane or magical writing vanishes.",
    "Expeditious Retreat: Your base land speed increases by 30 ft.",
    "Feather Fall: Objects or creatures fall slowly.",
    "Grease: Makes 10-ft. square or one object slippery.",
    "Hideous Laughter: Subject loses actions for 1 round/ level.",
    "Hypnotism: Fascinates 2d4 HD of creatures.",
    "Identify: Gives +10 bonus to identify magic items.",
    "Magic Aura: Alters object's magic aura.",
    "Magic MouthM: Objects speaks once when triggered.",
    "Obscure Object: Masks object against scrying.",
    "Remove Fear: Suppresses fear or gives +4 on saves against fear for one subject + one per four levels.",
    "Silent Image: Creates minor illusion of your design.",
    "Sleep: Puts 4 HD of creatures into magical slumber.",
    "Summon Monster I: Summons extraplanar creature to fight for you.",
    "Undetectable Alignment: Conceals alignment for 24 hours.",
    "Unseen Servant: Invisible force obeys your commands.",
    "Ventriloquism: Throws voice for 1 min./level.",
    ],
    2: [
    "Alter Self: Assume form of a Small or Medium humanoid.",
    "Animal Messenger: Sends a Tiny animal to a specific place.",
    "Animal Trance: Fascinates 2d6 HD of animals.",
    "Blindness/Deafness: Makes subject blind or deaf.",
    "Blur: Attacks miss subject 20% of the time.",
    "Calm Emotions: Calms creatures, negating emotion effects.",
    "Cat's Grace: Subject gains +4 to Dex for 1 min./level.",
    "Cure Moderate Wounds: Cures 2d8 damage + 1/level (max +10).",
    "Darkness: 20-ft. radius of supernatural shadow.",
    "Daze Monster: Living creature of 6 HD or less loses next action.",
    "Delay Poison: Stops poison from harming target for 1 hour/level.",
    "Detect Thoughts: Allows “listening” to surface thoughts.",
    "Eagle's Splendor: Subject gains +4 to Cha for 1 min./level.",
    "Enthrall: Captivates all within 100 ft. + 10 ft./level.",
    "Fox's Cunning: Subject gains +4 to Int for 1 min./level.",
    "Glitterdust: Blinds creatures, outlines invisible creatures.",
    "Heroism: Gives +2 on attack rolls, saves, skill checks.",
    "Hold Person: Paralyzes one humanoid for 1 round/level.",
    "Hypnotic Pattern: Fascinates (2d4 + level) HD of creatures.",
    "Invisibility: Subject is invisible for 1 min./level or until it attacks.",
    "Locate Object: Senses direction toward object (specific or type).",
    "Minor Image: As silent image, plus some sound.",
    "Mirror Image: Creates decoy duplicates of you (1d4 + 1 per three levels, max 8).",
    "Misdirection: Misleads divinations for one creature or object.",
    "Pyrotechnics: Turns fire into blinding light or choking smoke.",
    "Rage: Gives +2 to Str and Con, +1 on Will saves, –2 to AC.",
    "Scare: Panics creatures of less than 6 HD.",
    "Shatter: Sonic vibration damages objects or crystalline creatures.",
    "Silence: Negates sound in 20-ft. radius.",
    "Sound Burst: Deals 1d8 sonic damage and may stun subjects.",
    "Suggestion: Compels subject to follow stated course of action.",
    "Summon Monster II: Summons extraplanar creature to fight for you.",
    "Summon Swarm: Summons swarm of bats, rats, or spiders.",
    "Tongues: Speak and understand any language.",
    "Whispering Wind: Sends a short message 1 mile/level.",
    ],
    3: [
    "Blink: You randomly vanish and reappear for 1 round/level.",
    "Charm Monster: Makes monster believe it is your ally.",
    "Clairaudience/Clairvoyance: Hear or see at a distance for 1 min./level.",
    "Confusion: Subjects behave oddly for 1 round/level.",
    "Crushing Despair: Subjects take –2 on attack rolls, damage rolls, saves, and checks.",
    "Cure Serious Wounds: Cures 3d8 damage + 1/level (max +15).",
    "Daylight: 60-ft. radius of bright light.",
    "Deep Slumber: Puts 10 HD of creatures to sleep.",
    "Dispel Magic: Cancels one magical spell or effect.",
    "Displacement: Attacks miss subject 50% of the time.",
    "Fear: Subjects within cone flee for 1 round/level.",
    "Gaseous Form: Subject becomes insubstantial and can fly slowly.",
    "Geas, Lesser: Commands subject of 7 HD or less.",
    "Glibness: You gain +20 bonus on Bluff checks, and your lies can escape magical discernment.",
    "Good Hope: Subjects gain +2 on attack rolls, damage rolls, saves, and checks.",
    "Haste: One creature/level moves faster, receives +1 on attack rolls, AC, and Reflex saves.",
    "Illusory ScriptM: Only select creatures can read text.",
    "Invisibility Sphere: Makes everyone within 10 feet invisible.",
    "Major Image: As silent image, plus sound, smell, and thermal effects.",
    "Phantom Steed: Magic horse appears for 1 hour/level.",
    "Remove Curse: Frees object or person from curse.",
    "ScryingF: Spies on subject from a distance.",
    "Sculpt Sound: Creates new sounds or changes existing ones into new sounds.",
    "Secret Page: Changes one page to hide its real content.",
    "See Invisibility: Reveals invisible creatures or objects.",
    "Sepia Snake SigilM: Creates a snake-shaped text symbol that immobilizes reader.",
    "Slow: One subject/level takes only one action/round, –1 to AC, Reflex saves, and attack rolls.",
    "Speak with Animals: You can communicate with animals.",
    "Summon Monster III: Summons extraplanar creature to fight for you.",
    "Tiny Hut: Creates shelter for 10 creatures.",
    ],
    4: [
    "Break Enchantment: Frees subjects from enchantments, transmutations, and curses.",
    "Cure Critical Wounds: Cures 4d8 damage + 1/level (max +20).",
    "Detect Scrying: Alerts you to magical eavesdropping.",
    "Dimension Door: Teleports you a short distance.",
    "Dominate Person: Controls humanoid telepathically.",
    "Freedom of Movement: Subject moves normally despite impediments to restrict movement.",
    "Hallucinatory Terrain: Makes one type of terrain appear like another (field as forest, or the like).",
    "Hold Monster: As hold person, but any creature.",
    "Invisibility, Greater: As invisibility, but subject can attack and stay invisible.",
    "Legend LoreMF: Lets you learn tales about a person, place, or thing.",
    "Locate Creature: Indicates direction to known creature.",
    "Modify Memory: Changes 5 minutes of subject's memories.",
    "Neutralize Poison: Immunizes subject against poison, detoxifies venom in or on subject.",
    "Rainbow Pattern: Lights fascinate 24 HD of creatures.",
    "Repel Vermin: Insects, spiders, and other vermin stay 10 ft. away.",
    "Secure Shelter: Creates sturdy cottage.",
    "Shadow Conjuration: Mimics conjuration below 4th level, but only 20% real.",
    "Shout: Deafens all within cone and deals 5d6 sonic damage.",
    "Speak with Plants: You can talk to plants and plant creatures.",
    "Summon Monster IV: Summons extraplanar creature to fight for you.",
    "Zone of Silence: Keeps eavesdroppers from overhearing you.",
    ],
    5: [
    "Cure Light Wounds, Mass: Cures 1d8 damage + 1/level, affects 1 subject/level.",
    "Dispel Magic, Greater: Works as dispel magic, but can affect multiple targets.",
    "Dream: Sends message to anyone sleeping.",
    "False VisionM: Fools scrying with an illusion.",
    "Heroism, Greater: Gives +4 bonus on attack rolls, saves, skill checks; immunity to fear; temporary hp.",
    "Mind Fog: Subjects in fog get –10 to Wis and Will checks.",
    "Mirage Arcana: As hallucinatory terrain, plus structures.",
    "Mislead: Turns you invisible and creates illusory double.",
    "Nightmare: Sends vision dealing 1d10 damage, fatigue.",
    "Persistent Image: As major image, but no concentration required.",
    "Seeming: Changes appearance of one person per two levels.",
    "Shadow Evocation: Mimics evocation of lower than 5th level, but only 20% real.",
    "Shadow Walk: Step into shadow to travel rapidly.",
    "Song of Discord: Forces targets to attack each other.",
    "Suggestion, Mass: As suggestion, affects subject/level.",
    "Summon Monster V: Summons extraplanar creature to fight for you.",
    ],
    6: [
    "Analyze DweomerF: Reveals magical aspects of subject.",
    "Animate Objects: Objects attack your foes.",
    "Cat's Grace, Mass: As cat's grace, affects 1 subject/level.",
    "Charm Monster, Mass: As charm monster, but all within 30 ft.",
    "Cure Moderate Wounds, Mass: Cures 2d8 damage + 1/level, affects 1 subject/level.",
    "Eagle's Splendor, Mass: As eagle's splendor, affects 1 subject/level.",
    "Eyebite: Target becomes panicked, sickened, and/or comatose.",
    "Find the Path: Shows most direct way to a location.",
    "Fox's Cunning, Mass: As fox's cunning, affects 1 subject/level.",
    "Geas/Quest: As lesser geas, but affects any creature.",
    "Heroes' Feast: Food for one creature/level cures and grants combat bonuses.",
    "Irresistible Dance: Forces subject to dance.",
    "Permanent Image: Permanent illusion, includes sight, sound, smell, and thermal effects.",
    "Programmed ImageM: As major image, plus triggered by event.",
    "Project ImageM: Illusory double can talk and cast spells.",
    "Scrying, Greater: As scrying, but faster and longer.",
    "Shout, Greater: Devastating yell deals 10d6 sonic damage; stuns creatures.",
    "Summon Monster VI: Summons extraplanar creature to fight for you.",
    "Sympathetic Vibration: Deals 2d10 damage/round to freestanding structure.",
    "Veil: Changes appearance of group of creatures.",
    ]
  },
  /* =============== */
  /* Table: Cleric */
  /* =============== */
  cleric: {
    0: [
    "Bleed: Cause a stabilized creature to resume dying.",
    "Create Water: Creates 2 gallons/level of pure water.",
    "Detect Magic: Detects spells and magic items within 60 ft.",
    "Detect Poison: Detects poison in one creature or object.",
    "Guidance: +1 on one attack roll, saving throw, or skill check.",
    "Light: Object shines like a torch.",
    "Mending: Makes minor repairs on an object.",
    "Purify Food and Drink: Purifies 1 cu. ft./level of food or water.",
    "Read Magic: Read scrolls and spellbooks.",
    "Resistance: Subject gains +1 on saving throws.",
    "Stabilize: Cause a dying creature to stabilize.",
    "Virtue: Subject gains 1 temporary hp.",
    ],
    1: [
    "Bane: Enemies take –1 on attack rolls and saves against fear.",
    "Bless: Allies gain +1 on attack rolls and saves against fear.",
    "Bless WaterM: Makes holy water.",
    "Cause Fear: One creature of 5 HD or less flees for 1d4 rounds.",
    "Command: One subject obeys selected command for 1 round.",
    "Comprehend Languages: You understand all spoken and written languages.",
    "Cure Light Wounds: Cures 1d8 damage + 1/level (max +5).",
    "Curse WaterM: Makes unholy water.",
    "Deathwatch: Reveals how near death subjects within 30 ft. are.",
    "Detect Chaos/Evil/Good/Law: Reveals creatures, spells, or objects of selected alignment.",
    "Detect Undead: Reveals undead within 60 ft.",
    "Divine Favor: You gain +1 per three levels on attack and damage rolls.",
    "Doom: One subject takes –2 on attack rolls, damage rolls, saves, and checks.",
    "Endure Elements: Exist comfortably in hot or cold regions.",
    "Entropic Shield: Ranged attacks against you have 20% miss chance.",
    "Hide from Undead: Undead can't perceive one subject/level.",
    "Inflict Light Wounds: Touch deals 1d8 damage +1/level (max +5).",
    "Magic Stone: Three stones gain +1 on attack, deal 1d6 +1 damage.",
    "Magic Weapon: Weapon gains +1 bonus.",
    "Obscuring Mist: Fog surrounds you.",
    "Protection from Chaos/Evil/Good/Law: +2 to AC and saves, plus additional protection against selected alignment.",
    "Remove Fear: Suppresses fear or gives +4 on saves against fear for one subject + one per four levels.",
    "Sanctuary: Opponents can't attack you, and you can't attack.",
    "Shield of Faith: Aura grants +2 or higher deflection bonus.",
    "Summon Monster I: Summons extraplanar creature to fight for you.",
    ],
    2: [
    "Aid: +1 on attack rolls and saves against fear, 1d8 temporary hp +1/level (max +10).",
    "Align Weapon: Weapon becomes good, evil, lawful, or chaotic.",
    "AuguryMF: Learns whether an action will be good or bad.",
    "Bear's Endurance: Subject gains +4 to Con for 1 min./level.",
    "Bull's Strength: Subject gains +4 to Str for 1 min./level.",
    "Calm Emotions: Calms creatures, negating emotion effects.",
    "ConsecrateM: Fills area with positive energy, weakening undead.",
    "Cure Moderate Wounds: Cures 2d8 damage + 1/level (max +10).",
    "Darkness: 20-ft. radius of supernatural shadow.",
    "Death Knell: Kills dying creature; you gain 1d8 temporary hp, +2 to Str, and +1 caster level.",
    "Delay Poison: Stops poison from harming target for 1 hour/level.",
    "DesecrateM: Fills area with negative energy, making undead stronger.",
    "Eagle's Splendor: Subject gains +4 to Cha for 1 min./level.",
    "Enthrall: Captivates all within 100 ft. + 10 ft./level.",
    "Find Traps: Notice traps as a rogue does.",
    "Gentle Repose: Preserves one corpse.",
    "Hold Person: Paralyzes one humanoid for 1 round/level.",
    "Inflict Moderate Wounds: Touch attack, 2d8 damage + 1/level (max +10).",
    "Make Whole: Repairs an object.",
    "Owl's Wisdom: Subject gains +4 to Wis for 1 min./level.",
    "Remove Paralysis: Frees creatures from paralysis or slow effect.",
    "Resist Energy: Ignores 10 (or more) points of damage/attack from specified energy type.",
    "Restoration, Lesser: Dispels magical ability penalty or repairs 1d4 ability damage.",
    "Shatter: Sonic vibration damages objects or crystalline creatures.",
    "Shield OtherF: You take half of subject's damage.",
    "Silence: Negates sound in 20-ft. radius.",
    "Sound Burst: Deals 1d8 sonic damage to subjects; may stun them.",
    "Spiritual Weapon: Magic weapon attacks on its own.",
    "Status: Monitors condition, position of allies.",
    "Summon Monster II: Summons extraplanar creature to fight for you.",
    "Undetectable Alignment: Conceals alignment for 24 hours.",
    "Zone of Truth: Subjects within range cannot lie.",
    ],
    3: [
    "Animate DeadM: Creates undead skeletons and zombies.",
    "Bestow Curse: –6 to an ability score; –4 on attack rolls, saves, and checks; or 50% chance of losing each action.",
    "Blindness/Deafness: Makes subject blinded or deafened.",
    "Contagion: Infects subject with chosen disease.",
    "Continual FlameM: Makes a permanent, heatless light.",
    "Create Food and Water: Feeds three humans (or one horse)/level.",
    "Cure Serious Wounds: Cures 3d8 damage + 1/level (max +15).",
    "Daylight: 60-ft. radius of bright light.",
    "Deeper Darkness: Object sheds supernatural shadow in 60-ft. radius.",
    "Dispel Magic: Cancels one magical spell or effect.",
    "Glyph of WardingM: Inscription harms those who pass it.",
    "Helping Hand: Ghostly hand leads subject to you.",
    "Inflict Serious Wounds: Touch attack, 3d8 damage + 1/level (max +15).",
    "Invisibility Purge: Dispels invisibility within 5 ft./level.",
    "Locate Object: Senses direction toward object (specific or type).",
    "Magic Circle against Chaos/Evil/Good/Law: As protection spells, but 10-ft. radius and 10 min./level.",
    "Magic Vestment: Armor or shield gains +1 enhancement per four levels.",
    "Meld into Stone: You and your gear merge with stone.",
    "Obscure Object: Masks object against scrying.",
    "Prayer: Allies get +1 bonus on most rolls, enemies –1 penalty.",
    "Protection from Energy: Absorb 12 points/level of damage from one kind of energy.",
    "Remove Blindness/Deafness: Cures normal or magical blindness or deafness.",
    "Remove Curse: Frees object or person from curse.",
    "Remove Disease: Cures all diseases affecting subject.",
    "Searing Light: Ray deals 1d8/two levels damage (more against undead).",
    "Speak with Dead: Corpse answers one question/two levels.",
    "Stone Shape: Sculpts stone into any shape.",
    "Summon Monster III: Summons extraplanar creature to fight for you.",
    "Water Breathing: Subjects can breathe underwater.",
    "Water Walk: Subject treads on water as if solid.",
    "Wind Wall: Deflects arrows, smaller creatures, and gases."
    ],
    4: [
    "Air Walk: Subject treads on air as if solid (climb or descend at 45-degree angle).",
    "Chaos Hammer: Harms and slows lawful creatures (1d8 damage/2 levels).",
    "Control Water: Raises or lowers bodies of water.",
    "Cure Critical Wounds: Cures 4d8 damage + 1/level (max +20).",
    "Death Ward: Grants bonuses against death spells and negative energy.",
    "Dimensional Anchor: Bars extradimensional movement.",
    "Discern Lies: Reveals deliberate falsehoods.",
    "Dismissal: Forces a creature to return to native plane.",
    "DivinationM: Provides useful advice for specific proposed actions.",
    "Divine Power: You gain attack bonuses and 1 hp/level.",
    "Freedom of Movement: Subject moves normally despite impediments to movement.",
    "Giant Vermin: Turns centipedes, scorpions, or spiders into giant vermin.",
    "Holy Smite: Harms and possibly blinds evil creatures (1d8 damage/2 levels).",
    "Imbue with Spell Ability: Transfer spells to subject.",
    "Inflict Critical Wounds: Touch attack, 4d8 damage + 1/level (max +20).",
    "Magic Weapon, Greater: Weapon gains +1 bonus/four levels (max +5).",
    "Neutralize Poison: Immunizes subject against poison, detoxifies venom in or on subject.",
    "Order's Wrath: Harms and dazes chaotic creatures (1d8 damage/2 levels).",
    "Planar Ally, LesserM: Exchange services with a 6 HD extraplanar creature.",
    "Poison: Touch deals 1d3 Con damage 1/round for 6 rounds.",
    "Repel Vermin: Insects, spiders, and other vermin stay 10 ft. away.",
    "RestorationM: Restores level and ability score drains.",
    "Sending: Delivers short message anywhere, instantly.",
    "Spell Immunity: Subject is immune to one spell per 4 levels.",
    "Summon Monster IV: Summons extraplanar creature to fight for you.",
    "Tongues: Speak and understand any language.",
    "Unholy Blight: Harms and sickens good creatures (1d8 damage/2 levels).",
    ],
    5: [
    "AtonementFM: Removes burden of misdeeds from subject and reverses magical alignment change.",
    "Break Enchantment: Frees subjects from enchantments, transmutations, and curses.",
    "Breath of Life: Cures 5d8 damage + 1/level and restores life to recently slain creatures.",
    "Command, Greater: As command, but affects one subject/level.",
    "CommuneM: Deity answers one yes-or-no question/level.",
    "Cure Light Wounds, Mass: Cures 1d8 damage + 1/level, affects 1 subject/level.",
    "Dispel Chaos/Evil/Good/Law: +4 bonus against attacks.",
    "Disrupting Weapon: Melee weapon destroys undead.",
    "Flame Strike: Smites foes with divine fire (1d6/level damage).",
    "HallowM: Designates location as holy.",
    "Inflict Light Wounds, Mass: Deals 1d8 damage + 1/level, affects 1 subject/level.",
    "Insect Plague: Wasp swarms attack creatures.",
    "Mark of Justice: Designates action that triggers curse on subject.",
    "Plane ShiftF: As many as 8 subjects travel to another plane.",
    "Raise DeadM: Restores life to subject who died as long as one day/level ago.",
    "Righteous Might: Your size increases, and you gain bonuses in combat.",
    "ScryingF: Spies on subject from a distance.",
    "Slay Living: Touch attack deals 12d6 + 1 per level.",
    "Spell Resistance: Subject gains SR 12 + level.",
    "Summon Monster V: Summons extraplanar creature to fight for you.",
    "Symbol of PainM: Triggered rune wracks nearby creatures with pain.",
    "Symbol of SleepM: Triggered rune puts nearby creatures into catatonic slumber.",
    "True SeeingM: Lets you see all things as they really are.",
    "UnhallowM: Designates location as unholy.",
    "Wall of Stone: Creates a stone wall that can be shaped.",
    ],
    6: [
    "Animate Objects: Objects attack your foes.",
    "Antilife Shell: 10-ft.-radius field hedges out living creatures.",
    "Banishment: Banishes 2 HD/level of extraplanar creatures.",
    "Bear's Endurance, Mass: As bear's endurance, affects 1 subject/level.",
    "Blade Barrier: Wall of blades deals 1d6/level damage.",
    "Bull's Strength, Mass: As bull's strength, affects 1 subject/level.",
    "Create UndeadM: Create ghasts, ghouls, mohrgs, or mummies.",
    "Cure Moderate Wounds, Mass: Cures 2d8 damage + 1/level, affects 1 subject/level.",
    "Dispel Magic, Greater: As dispel magic, but with multiple targets.",
    "Eagle's Splendor, Mass: As eagle's splendor, affects 1 subject/level.",
    "Find the Path: Shows most direct way to a location.",
    "ForbiddanceM: Blocks planar travel, damages creatures of different alignment.",
    "Geas/Quest: As lesser geas, but affects any creature.",
    "Glyph of Warding, GreaterM: As glyph of warding, but up to 10d8 damage or 6th-level spell.",
    "Harm: Deals 10 points/level damage to target.",
    "Heal: Cures 10 points/level damage, all diseases and mental conditions.",
    "Heroes' Feast: Food for one creature/level cures and grants combat bonuses.",
    "Inflict Moderate Wounds, Mass: Deals 2d8 damage + 1/level, affects 1 subject/level.",
    "Owl's Wisdom, Mass: As owl's wisdom, affects 1 subject/level.",
    "Planar AllyM: As lesser planar ally, but up to 12 HD.",
    "Summon Monster VI: Summons extraplanar creature to fight for you.",
    "Symbol of FearM: Triggered rune panics nearby creatures.",
    "Symbol of PersuasionM: Triggered rune charms nearby creatures.",
    "Undeath to DeathM: Destroys 1d4 HD/level undead (max. 20d4).",
    "Wind Walk: You and your allies turn vaporous and travel fast.",
    "Word of Recall: Teleports you back to designated place.",
    ],
    7: [
    "Blasphemy: Kills, paralyzes, weakens, or dazes nonevil subjects.",
    "Control Weather: Changes weather in local area.",
    "Cure Serious Wounds, Mass: Cures 3d8 damage + 1/level, affects 1 subject/level.",
    "DestructionF: Kills subject and destroys remains.",
    "Dictum: Kills, paralyzes, staggers, or deafens nonlawful targets.",
    "Ethereal Jaunt: You become ethereal for 1 round/level.",
    "Holy Word: Kills, paralyzes, blinds, or deafens nongood subjects.",
    "Inflict Serious Wounds, Mass: Deals 3d8 damage + 1/level, affects 1 subject/level.",
    "RefugeM: Alters item to transport its possessor to you.",
    "Regenerate: Subject's severed limbs grow back, cures 4d8 damage +1/level (max +35).",
    "Repulsion: Creatures can't approach you.",
    "Restoration, GreaterM: As restoration, plus restores all levels and ability scores.",
    "ResurrectionM: Fully restore dead subject.",
    "Scrying, Greater: As scrying, but faster and longer.",
    "Summon Monster VII: Summons extraplanar creature to fight for you.",
    "Symbol of StunningM: Triggered rune stuns nearby creatures.",
    "Symbol of WeaknessM: Triggered rune weakens nearby creatures.",
    "Word of Chaos: Kills, confuses, stuns, or deafens nonchaotic subjects.",
    ],
    8: [
    "Antimagic Field: Negates magic within 10 ft.",
    "Cloak of ChaosF: +4 to AC, +4 resistance, and SR 25 against lawful spells.",
    "Create Greater UndeadM: Create shadows, wraiths, spectres, or devourers.",
    "Cure Critical Wounds, Mass: Cures 4d8 damage + 1/level for many creatures.",
    "Dimensional Lock: Teleportation and interplanar travel blocked for 1 day/level.",
    "Discern Location: Reveals exact location of creature or object.",
    "Earthquake: Intense tremor shakes 80-ft. radius.",
    "Fire Storm: Deals 1d6/level fire damage.",
    "Holy AuraF: +4 to AC, +4 resistance, and SR 25 against evil spells.",
    "Inflict Critical Wounds, Mass: Deals 4d8 damage + 1/level, affects 1 subject/level.",
    "Planar Ally, GreaterM: As lesser planar ally, but up to 18 HD.",
    "Shield of LawF: +4 to AC, +4 resistance, and SR 25 against chaotic spells.",
    "Spell Immunity, Greater: As spell immunity, but up to 8th-level spells.",
    "Summon Monster VIII: Summons extraplanar creature to fight for you.",
    "Symbol of DeathM: Triggered rune kills nearby creatures.",
    "Symbol of InsanityM: Triggered rune renders nearby creatures insane.",
    "Unholy AuraF: +4 to AC, +4 resistance, and SR 25 against good spells.",
    ],
    9: [
    "Astral ProjectionM: Projects you and others onto Astral Plane.",
    "Energy Drain: Subject gains 2d4 negative levels.",
    "Etherealness: Travel to Ethereal Plane with companions.",
    "GateM: Connects two planes for travel or summoning.",
    "Heal, Mass: As heal, but affects 1 subject/level.",
    "Implosion: Inflict 10 damage/level to one creature/round.",
    "MiracleM: Requests a deity's intercession.",
    "Soul BindF: Traps newly dead soul to prevent resurrection.",
    "Storm of Vengeance: Storm rains acid, lightning, and hail.",
    "Summon Monster IX: Summons extraplanar creature to fight for you.",
    "True ResurrectionM: As resurrection, plus remains aren't needed.",
    ]
  },
  /* =============== */
  /* Table: Druid    */
  /* =============== */
  druid: {
    0: [
    "Create Water: Creates 2 gallons/level of pure water.",
    "Detect Magic: Detects spells and magic items within 60 ft.",
    "Detect Poison: Detects poison in one creature or object.",
    "Flare: Dazzles one creature (–1 penalty on attack rolls).",
    "Guidance: +1 on one attack roll, saving throw, or skill check.",
    "Know Direction: You discern north.",
    "Light: Object shines like a torch.",
    "Mending: Makes minor repairs on an object.",
    "Purify Food and Drink: Purifies 1 cu. ft./level of food or water.",
    "Read Magic: Read scrolls and spellbooks.",
    "Resistance: Subject gains +1 bonus on saving throws.",
    "Stabilize: Cause a dying creature to stabilize.",
    "Virtue: Subject gains 1 temporary hp.",
    ],
    1: [
    "Calm Animals: Calms 2d4 + level HD of animals.",
    "Charm Animal: Makes one animal your friend.",
    "Cure Light Wounds: Cures 1d8 damage + 1/level (max +5).",
    "Detect Animals or Plants: Detects kinds of animals or plants.",
    "Detect Snares and Pits: Reveals natural or primitive traps.",
    "Endure Elements: Exist comfortably in hot or cold regions.",
    "Entangle: Plants entangle everyone in 40-ft. radius.",
    "Faerie Fire: Outlines subjects with light, canceling blur, concealment, and the like.",
    "Goodberry: 2d4 berries each cure 1 hp (max 8 hp/24 hours).",
    "Hide from Animals: Animals can't perceive one subject/level.",
    "Jump: Subject gets bonus on Acrobatics checks.",
    "Longstrider: Your speed increases by 10 ft.",
    "Magic Fang: One natural weapon of subject creature gets +1 on attack and damage rolls.",
    "Magic Stone: Three stones gain +1 on attack rolls, deal 1d6+1 damage.",
    "Obscuring Mist: Fog surrounds you.",
    "Pass without Trace: One subject/level leaves no tracks.",
    "Produce Flame: 1d6 damage + 1/level, touch or thrown.",
    "Shillelagh: Cudgel or quarterstaff becomes +1 weapon (2d6 damage) for 1 min./level.",
    "Speak with Animals: You can communicate with animals.",
    "Summon Nature's Ally I: Summons creature to fight.",
    ],
    2: [
    "Animal Messenger: Sends a Tiny animal to a specific place.",
    "Animal Trance: Fascinates 2d6 HD of animals.",
    "Barkskin: Grants +2 (or higher) enhancement to natural armor.",
    "Bear's Endurance: Subject gains +4 to Con for 1 min./level.",
    "Bull's Strength: Subject gains +4 to Str for 1 min./level.",
    "Cat's Grace: Subject gains +4 to Dex for 1 min./level.",
    "Chill Metal: Cold metal damages those who touch it.",
    "Delay Poison: Stops poison from harming subject for 1 hour/level.",
    "Fire TrapM: Opened object deals 1d4 + 1/level damage.",
    "Flame Blade: Touch attack deals 1d8 + 1/two levels damage.",
    "Flaming Sphere: Rolling ball of fire deals 3d6 fire damage.",
    "Fog Cloud: Fog obscures vision.",
    "Gust of Wind: Blows away or knocks down smaller creatures.",
    "Heat Metal: Makes metal so hot it damages those who touch it.",
    "Hold Animal: Paralyzes one animal for 1 round/level.",
    "Owl's Wisdom: Subject gains +4 to Wis for 1 min./level.",
    "Reduce Animal: Shrinks one willing animal.",
    "Resist Energy: Ignores 10 or more points of damage per attack from specified energy type.",
    "Restoration, Lesser: Dispels magical ability penalty or repairs 1d4 ability damage.",
    "Soften Earth and Stone: Turns stone to clay, or dirt to sand or mud.",
    "Spider Climb: Grants ability to walk on walls and ceilings.",
    "Summon Nature's Ally II: Summons creature to fight.",
    "Summon Swarm: Summons swarm of bats, rats, or spiders.",
    "Tree Shape: You look exactly like a tree for 1 hour/level.",
    "Warp Wood: Bends wood.",
    "Wood Shape: Reshapes wooden objects to suit you.",
    ],
    3: [
    "Call Lightning: Calls down lightning bolts (3d6 per bolt) from sky.",
    "Contagion: Infects subject with chosen disease.",
    "Cure Moderate Wounds: Cures 2d8 damage + 1/level (max +10).",
    "Daylight: 60-ft. radius of bright light.",
    "Diminish Plants: Reduces size or blights the growth of normal plants.",
    "Dominate Animal: One animal obeys your silent mental commands and orders.",
    "Magic Fang, Greater: One natural weapon gets + 1/four levels (max +5).",
    "Meld into Stone: You and your gear merge with stone.",
    "Neutralize Poison: Immunizes subject against poison, detoxifies venom in or on subject.",
    "Plant Growth: Grows vegetation, improves crops.",
    "Poison: Touch deals 1d3 Con damage 1/round for 6 rounds.",
    "Protection from Energy: Absorbs 12 points/level of damage from one kind of energy.",
    "Quench: Extinguishes fires.",
    "Remove Disease: Cures all diseases affecting subject.",
    "Sleet Storm: Hampers vision and movement.",
    "Snare: Creates a magic booby trap.",
    "Speak with Plants: You can talk to plants and plant creatures.",
    "Spike Growth: Creatures in area take 1d4 damage, may be slowed.",
    "Stone Shape: Sculpts stone into any shape.",
    "Summon Nature's Ally III: Summons creature to fight.",
    "Water Breathing: Subjects can breathe underwater.",
    "Wind Wall: Deflects arrows, smaller creatures, and gases.",
    ],
    4: [
    "Air Walk: Subject treads on air as if solid (climb or descend at 45-degree angle).",
    "Antiplant Shell: Keeps animated plants at bay.",
    "Blight: Withers one plant or deals 1d6/level damage to plant creature.",
    "Command Plants: Sways the actions of plant creatures.",
    "Control Water: Raises or lowers bodies of water.",
    "Cure Serious Wounds: Cures 3d8 damage + 1/level (max +15).",
    "Dispel Magic: Cancels one magical spell or effect.",
    "Flame Strike: Smites foes with divine fire (1d6/level damage).",
    "Freedom of Movement: Subject moves normally despite impediments to movement.",
    "Giant Vermin: Turns centipedes, scorpions, or spiders into giant vermin.",
    "Ice Storm: Hail deals 5d6 damage in cylinder 40 ft. across.",
    "Reincarnate: Brings dead subject back in a random body.",
    "Repel Vermin: Insects, spiders, and other vermin stay 10 ft. away.",
    "Rusting Grasp: Your touch corrodes iron and alloys.",
    "ScryingF: Spies on subject from a distance.",
    "Spike Stones: Creatures in area take 1d8 damage, may also be slowed.",
    "Summon Nature's Ally IV: Summons creature to fight.",
    ],
    5: [
    "Animal Growth: One animal doubles in size.",
    "AtonementFM: Removes burden of misdeeds from subject.",
    "AwakenM: Animal or tree gains human intellect.",
    "Baleful Polymorph: Transforms subject into harmless animal.",
    "Call Lightning Storm: As call lightning, but 5d6 damage per bolt.",
    "Commune with Nature: Learn about terrain for 1 mile/level.",
    "Control Winds: Changes wind direction and speed.",
    "Cure Critical Wounds: Cures 4d8 damage + 1/level (max +20).",
    "Death Ward: Grants bonuses against death spells and negative energy.",
    "HallowM: Designates location as holy.",
    "Insect Plague: Wasp swarms attack creatures.",
    "StoneskinM: Grants DR 10/adamantine.",
    "Summon Nature's Ally V: Summons creature to fight.",
    "Transmute Mud to Rock: Transforms two 10-ft. cubes per level.",
    "Transmute Rock to Mud: Transforms two 10-ft. cubes per level.",
    "Tree Stride: Step from one tree to another far away.",
    "UnhallowM: Designates location as unholy.",
    "Wall of Fire: Deals 2d4 fire damage out to 10 ft. and 1d4 out to 20 ft. Passing through wall deals 2d6 damage +1/level.",
    "Wall of Thorns: Thorns damage anyone who tries to pass.",
    ],
    6: [
    "Antilife Shell: 10-ft.-radius field hedges out living creatures.",
    "Bear's Endurance, Mass: As bear's endurance, affects 1 subject/level.",
    "Bull's Strength, Mass: As bull's strength, affects 1 subject/level.",
    "Cat's Grace, Mass: As cat's grace, affects one subject/level.",
    "Cure Light Wounds, Mass: Cures 1d8 damage + 1/level, affects 1 subject/level.",
    "Dispel Magic, Greater: As dispel magic, but with multiple targets.",
    "Find the Path: Shows most direct way to a location.",
    "Fire Seeds: Acorns and berries become grenades and bombs.",
    "Ironwood: Magic wood is as strong as steel.",
    "Liveoak: Oak becomes treant guardian.",
    "Move Earth: Digs trenches and builds hills.",
    "Owl's Wisdom, Mass: As owl's wisdom, affects 1 subject/level.",
    "Repel Wood: Pushes away wooden objects.",
    "Spellstaff: Stores one spell in wooden quarterstaff.",
    "Stone Tell: Talk to natural or worked stone.",
    "Summon Nature's Ally VI: Summons creature to fight.",
    "Transport via Plants: Move instantly from one plant to another of the same kind.",
    "Wall of Stone: Creates a stone wall that can be shaped.",
    ],
    7: [
    "Animate Plants: One or more plants animate and fight for you.",
    "Changestaff: Your staff becomes a treant on command.",
    "Control Weather: Changes weather in local area.",
    "Creeping Doom: Swarms of centipedes attack at your command.",
    "Cure Moderate Wounds, Mass: Cures 2d8 damage + 1/level, affects 1 subject/level.",
    "Fire Storm: Deals 1d6/level fire damage.",
    "Heal: Cures 10 points/level damage, all diseases and mental conditions.",
    "Scrying, Greater: As scrying, but faster and longer.",
    "Summon Nature's Ally VII: Summons creature to fight.",
    "Sunbeam: Beam blinds and deals 4d6 damage.",
    "Transmute Metal to Wood: Metal within 40 ft. becomes wood.",
    "True SeeingM: Lets you see all things as they really are.",
    "Wind Walk: You and your allies turn vaporous and travel fast.",
    ],
    8: [
    "Animal Shapes: One ally/level polymorphs into chosen animal.",
    "Control Plants: Controls actions of one or more plant creatures.",
    "Cure Serious Wounds, Mass: Cures 3d8 damage + 1/level, affects 1 subject/level.",
    "Earthquake: Intense tremor shakes 80-ft.-radius.",
    "Finger of Death: Deals 10 damage/level to one subject.",
    "Repel Metal or Stone: Pushes away metal and stone.",
    "Reverse Gravity: Objects and creatures fall upward.",
    "Summon Nature's Ally VIII: Summons creature to fight.",
    "Sunburst: Blinds all within 10 ft., deals 6d6 damage.",
    "Whirlwind: Cyclone deals damage and can pick up creatures.",
    "Word of Recall: Teleports you back to designated place.",
    ],
    9: [
    "Antipathy: Object or location affected by spell repels certain creatures.",
    "Cure Critical Wounds, Mass: Cures 4d8 damage + 1/level for many creatures.",
    "Elemental Swarm: Summons multiple elementals.",
    "Foresight: “Sixth sense” warns of impending danger.",
    "Regenerate: Subject's severed limbs grow back, cures 4d8 damage +1/level (max +35).",
    "Shambler: Creates 1d4+2 shambling mounds to fight for you.",
    "ShapechangeF: Transforms you into certain creatures, and you can change forms once per round.",
    "Storm of Vengeance: Storm rains acid, lightning, and hail.",
    "Summon Nature's Ally IX: Summons creature to fight.",
    "SympathyM: Object or location attracts certain creatures.",
    ]
  },
  /* =============== */
  /* Table: Paladin  */
  /* =============== */
  paladin: {
    1: [
    "Bless: Allies gain +1 on attack rolls and saves against fear.",
    "Bless WaterM: Makes holy water.",
    "Bless Weapon: Weapon strikes true against evil foes.",
    "Create Water: Creates 2 gallons/level of pure water.",
    "Cure Light Wounds: Cures 1d8 damage + 1/level (max +5).",
    "Detect Poison: Detects poison in one creature or small object.",
    "Detect Undead: Reveals undead within 60 ft.",
    "Divine Favor: You gain +1 per three levels on attack and damage rolls.",
    "Endure Elements: Exist comfortably in hot or cold regions.",
    "Magic Weapon: Weapon gains +1 bonus.",
    "Protection from Chaos/Evil: +2 to AC and saves, plus additional protection against selected alignment.",
    "Read Magic: Read scrolls and spellbooks.",
    "Resistance: Subject gains +1 on saving throws.",
    "Restoration, Lesser: Dispels magical ability penalty or repairs 1d4 ability damage.",
    "Virtue: Subject gains 1 temporary hp.",
    ],
    2: [
    "Bull's Strength: Subject gains +4 to Str for 1 min./level.",
    "Delay Poison: Stops poison from harming subject for 1 hour/level.",
    "Eagle's Splendor: Subject gains +4 to Cha for 1 min./level.",
    "Owl's Wisdom: Subject gains +4 to Wis for 1 min./level.",
    "Remove Paralysis: Frees one or more creatures from paralysis or slow effect.",
    "Resist Energy: Ignores 10 or more points of damage per attack from specified energy type.",
    "Shield OtherF: You take half of subject's damage.",
    "Undetectable Alignment: Conceals alignment from magical detection for 24 hours.",
    "Zone of Truth: Subjects within range cannot lie.",
    ],
    3: [
    "Cure Moderate Wounds: Cures 2d8 damage +1/level (max. +10).",
    "Daylight: 60-ft. radius of bright light.",
    "Discern Lies: Reveals deliberate falsehoods.",
    "Dispel Magic: Cancels one magical spell or effect.",
    "Heal Mount: As heal on horse or other special mount.",
    "Magic Circle against Chaos/Evil: As protection from chaos, but 10-ft. radius and 10 min./level.",
    "Magic Weapon, Greater: Weapon gains +1 bonus/four levels (max +5).",
    "Prayer: Allies get +1 bonus on most rolls, enemies –1 penalty.",
    "Remove Blindness/Deafness: Cures normal or magical blindness or deafness.",
    "Remove Curse: Frees object or person from curse.",
    ],
    4: [
    "Break Enchantment: Frees subjects from enchantments, transmutations, and curses.",
    "Cure Serious Wounds: Cures 3d8 damage + 1/level (max +15).",
    "Death Ward: Grants bonuses against death spells and negative energy.",
    "Dispel Chaos: +4 bonus against attacks by chaotic creatures.",
    "Dispel Evil: +4 bonus against attacks by evil creatures.",
    "Holy Sword: Weapon becomes +5, deals +2d6 damage against evil.",
    "Mark of Justice: Designates action that triggers curse on subject.",
    "Neutralize Poison: Immunizes subject against poison, detoxifies venom in or on subject.",
    "RestorationM: Restores level and ability score drains.",
    ]
  },
  /* =============== */
  /* Table: Ranger   */
  /* =============== */
  ranger: {
    1: [
    "Alarm: Wards an area for 2 hours/level.",
    "Animal Messenger: Sends a Tiny animal to a specific place.",
    "Calm Animals: Calms 2d4 + level HD of animals.",
    "Charm Animal: Makes one animal your friend.",
    "Delay Poison: Stops poison from harming subject for 1 hour/level.",
    "Detect Animals or Plants: Detects kinds of animals or plants.",
    "Detect Poison: Detects poison in one creature or object.",
    "Detect Snares and Pits: Reveals natural or primitive traps.",
    "Endure Elements: Exist comfortably in hot or cold regions.",
    "Entangle: Plants entangle everyone in 40-ft. radius.",
    "Hide from Animals: Animals can't perceive one subject/level.",
    "Jump: Subject gets bonus on Acrobatics checks.",
    "Longstrider: Your base speed increases by 10 ft.",
    "Magic Fang: One natural weapon of subject creature gets +1 on attack and damage rolls.",
    "Pass without Trace: One subject/level leaves no tracks.",
    "Read Magic: Read scrolls and spellbooks.",
    "Resist Energy: Ignores 10 (or more) points of damage/attack from specified energy type.",
    "Speak with Animals: You can communicate with animals.",
    "Summon Nature's Ally I: Summons creature to fight for you.",
    ],
    2: [
    "Barkskin: Grants +2 (or higher) enhancement to natural armor.",
    "Bear's Endurance: Subject gains +4 to Con for 1 min./level.",
    "Cat's Grace: Subject gains +4 to Dex for 1 min./level.",
    "Cure Light Wounds: Cures 1d8 damage + 1/level (max +5).",
    "Hold Animal: Paralyzes one animal for 1 round/level.",
    "Owl's Wisdom: Subject gains +4 to Wis for 1 min./level.",
    "Protection from Energy: Absorbs 12 points/level of damage from one kind of energy.",
    "Snare: Creates a magic booby trap.",
    "Speak with Plants: You can talk to plants and plant creatures.",
    "Spike Growth: Creatures in area take 1d4 damage, may be slowed.",
    "Summon Nature's Ally II: Summons creature to fight for you.",
    "Wind Wall: Deflects arrows, smaller creatures, and gases.",
    ],
    3: [
    "Command Plants: Sway the actions of plant creatures.",
    "Cure Moderate Wounds: Cures 2d8 damage +1/level (max. +10).",
    "Darkvision: See 60 ft. in total darkness.",
    "Diminish Plants: Reduces size or blights growth of normal plants.",
    "Magic Fang, Greater: One natural weapon gets + 1/four levels (max. +5).",
    "Neutralize Poison: Immunizes subject against poison, detoxifies venom in or on subject.",
    "Plant Growth: Grows vegetation, improves crops.",
    "Reduce Animal: Shrinks one willing animal.",
    "Remove Disease: Cures all diseases affecting subject.",
    "Repel Vermin: Insects, spiders, and other vermin stay 10 ft. away.",
    "Summon Nature's Ally III: Summons creature to fight for you.",
    "Tree Shape: You look exactly like a tree for 1 hour/level.",
    "Water Walk: Subject treads on water as if solid.",
    ],
    4: [
    "Animal Growth: One animal doubles in size.",
    "Commune with Nature: Learn about terrain for 1 mile/level.",
    "Cure Serious Wounds: Cures 3d8 damage + 1/level (max +15).",
    "Freedom of Movement: Subject moves normally despite impediments to movement.",
    "NondetectionM: Hides subject from divination, scrying.",
    "Summon Nature's Ally IV: Summons creature to fight for you.",
    "Tree Stride: Step from one tree to another far away.",
    ]
  },
  /* =============== */
  /* Table: Shaman   */
  /* =============== */
  shaman: {
    0: [
      "Arcane mark",
      "bleed",
      "create water",
      "dancing lights",
      "daze",
      "detect magic",
      "detect poison",
      "guidance",
      "know direction",
      "light",
      "mending",
      "purify food and drink",
      "read magic",
      "resistance",
      "stabilize",
      "touch of fatigue",
      "virtue"
    ],
    1: [
      "Bane",
      "blend",
      "bless",
      "burning hands",
      "calm animals",
      "cause fear",
      "charm animal",
      "charm person",
      "chill touch",
      "comprehend languages",
      "cure light wounds",
      "dancing lantern",
      "detect animals or plants",
      "detect chaos/evil/good/law",
      "detect undead",
      "discern next of kin",
      "doom",
      "endure elements",
      "entangle",
      "frostbite",
      "gentle breeze",
      "goodberry",
      "heightened awareness",
      "hex vulnerability",
      "hex ward",
      "hide from animals",
      "hydraulic push",
      "inflict light wounds",
      "magic stone",
      "magic weapon",
      "monkey fish",
      "obscuring mist",
      "pass without trace",
      "produce flame",
      "protection from chaos/evil/good/law",
      "remove fear",
      "sense spirit magic",
      "sleep",
      "stone shield",
      "thorn javelin",
      "wave shield"
    ],
    2: ["Aid", "alter self", "animal messenger", "animal purpose training", "animate dead (lesser)", "augury", "barkskin", "bear's endurance", "beastspeak", "bull's strength", "buoyancy", "burning gaze", "calm emotions", "commune with birds", "cure moderate wounds", "darkness", "delay poison", "eagle eye", "eagle's splendor", "enthrall", "false life", "flame blade", "focused scrutiny", "fog cloud", "gentle repose", "ghostbane dirge", "glide", "guiding star", "hold person", "imbue with elemental might", "inflict moderate wounds", "levitate", "life pact", "owl's wisdom", "remove paralysis", "resist energy", "restoration (lesser)", "scare", "shield companion", "sickening entanglement", "spiritual weapon", "summon swarm", "tree shape", "warp wood", "web shelter", "wood shape"
    ],
    3: ["Anchored step", "animate dead", "aura sight", "bestow curse", "blindness/deafness", "call lightning", "clairvoyance/clairaudience", "create food and water", "cure serious wounds", "daylight", "deep slumber", "deeper darkness", "dispel magic", "dominate animal", "fins to feet", "fly", "font of spirit magic", "hex glyph", "inflict serious wounds", "magic circle against chaos/evil/good/law", "magic vestment", "mantle of calm", "mindlocked messenger", "nauseating trail", "pierce disguise", "polymorph familiar", "protection from energy", "remove blindness/deafness", "remove curse", "sleet storm", "speak with dead", "speak with haunt", "stench of prey", "stinking cloud", "stone shape", "stricken heart", "thorny entanglement", "ward of the season", "water breathing", "water walk", "wind wall"
    ],
    4: ["Adjustable polymorph", "air geyser", "anti-incorporeal shell", "ball lightning", "command plants", "control water", "cure critical wounds", "curse of burning sleep", "detect scrying", "dismissal", "divination", "divine power", "earth glide", "false life (greater)", "familiar melding", "fear", "giant vermin", "ice storm", "imbue with spell ability", "inflict critical wounds", "magic weapon (greater)", "neutralize poison", "persistent vigor", "planar ally (lesser)", "poison", "rain of frogs", "reincarnate", "repel vermin", "restoration", "ride the waves", "sands of time", "scrying", "sending", "slowing mud", "solid fog", "spike stones", "spit venom", "thorn body", "tongues", "wandering star motes"
    ],
    5: ["Animal growth", "baleful polymorph", "blight", "break enchantment", "breath of life", "call lightning storm", "commune", "commune with nature", "control winds", "cure light wounds (mass)", "curse (major)", "dispel chaos/evil/good/law", "dominate person", "feast on fear", "flame strike", "ghostbane dirge (mass)", "grove of respite", "hex glyph (greater)", "inflict light wounds (mass)", "insect plague", "overland flight", "rest eternal", "stoneskin", "true seeing", "wall of fire", "wall of thorns"
    ],
    6: ["Antilife shell", "awaken", "banishment", "bear's endurance (mass)", "bull's strength (mass)", "cone of cold", "create undead", "cure moderate wounds (mass)", "dispel magic (greater)", "eagle's splendor (mass)", "find the path", "fire seeds", "flesh to stone", "inflict moderate wounds (mass)", "owl's wisdom (mass)", "planar ally", "raise dead", "slay living", "snake staff", "stone to flesh", "wall of stone"
    ],
    7: ["Animate plants", "cloak of dreams", "control weather", "creeping doom", "cure serious wounds (mass)", "fairy ring retreat", "harm", "heal", "ice body", "inflict serious wounds (mass)", "liveoak", "plane shift", "regenerate", "restoration (greater)", "scrying (greater)", "stone tell", "sunbeam", "transport via plants", "vision", "vortex", "wind walk"
    ],
    8: ["Animal shapes", "blood mist", "circle of clarity", "create greater undead", "cure critical wounds (mass)", "destruction", "discern location", "earthquake", "fire storm", "horrid wilting", "inflict critical wounds (mass)", "irresistible dance", "planar ally (greater)", "resurrection", "stormbolts", "sunburst", "whirlwind"
    ],
    9: ["Elemental swarm", "energy drain", "etherealness", "foresight", "heal (mass)", "polar midnight", "shambler", "shapechange", "soul bind", "storm of vengeance", "tsunami", "wail of the banshee", "winds of vengeance"
    ]
  },
  /* =============== */
  /* Table: Witch   */
  /* =============== */
  witch: {
    0: ["Arcane Mark", "Bleed", "Dancing Lights", "Daze", "Detect Magic", "Detect Poison", "Guidance", "Light", "Mending", "Message", "Putrefy Food and Drink", "Read Magic", "Resistance", "Spark", "Stabilize", "Touch of Fatigue"
    ],
    1: ["beguiling gift*, burning hands, cause fear, charm person, chill touch, command, comprehend languages, cure light wounds, dancing lantern*, detect secret doors, enlarge person, hypnotism, identify, ill omen*, inflict light wounds, mage armor, mask dweomer*, mount, obscuring mist, ray of enfeeblement, reduce person, sleep, summon monster I, unseen servant"
    ],
    2: ["alter self, augury, blindness/deafness, burning gaze*, cure moderate wounds, daze monster, death knell, delay poison, detect thoughts, enthrall, false life, feast of ashes*, fester*, find traps, fog cloud, gentle repose, glide*, glitterdust, hidden speech*, hold person, inflict moderate wounds, levitate, perceive cues*, pox pustules*, scare, see invisibility, spectral hand, status, summon monster II, summon swarm, touch of idiocy, vomit swarm*, web, zone of truth"
    ],
    3: ["arcane sight, bestow curse, clairaudience/clairvoyance, cup of dust*, deep slumber, dispel magic, fly, glyph of warding, guiding star*, heroism, lightning bolt, locate object, nature's exile*, pain strike*, rage, ray of exhaustion, remove blindness/deafness, remove curse, remove disease, screech*, seek thoughts*, sepia snake sigil, share senses*, sleet storm, speak with dead, stinking cloud, suggestion, summon monster III, tongues, twilight knife*, vampiric touch, water walk"
    ],
    4: ["arcane eye, black tentacles, charm monster, confusion, crushing despair, cure serious wounds, death ward, detect scrying, dimension door, discern lies, divination, enervation, fear, geas (lesser), ice storm, inflict serious wounds, locate creature, minor creation, moonstruck*, neutralize poison, phantasmal killer, poison, scrying, secure shelter, sleepwalk*, solid fog, spite*, summon monster IV, threefold aspect*, wandering star motes*"
    ],
    5: ["baleful polymorph, banish seeming*, blight, break enchantment, cloudkill, contact other plane, cure critical wounds, dominate person, feeblemind, hold monster, inflict critical wounds, magic jar, major creation, mark of justice, mind fog, overland flight, pain strike (mass)*, prying eyes, reincarnate, rest eternal*, secret chest, suffocation*, summon monster V, symbol of pain, symbol of sleep, telepathic bond, teleport, waves of fatigue"
    ],
    6: ["analyze dweomer, animate objects, cloak of dreams*, cone of cold, cure light wounds (mass), dispel magic (greater), eyebite, fester (mass)*, find the path, flesh to stone, geas/quest, guards and wards, heroism (greater), inflict light wounds (mass), legend lore, raise dead, slay living, stone to flesh, suggestion (mass), summon monster VI, swarm skin*, symbol of fear, symbol of persuasion, transformation, true seeing, unwilling shield*"
    ],
    7: ["arcane sight (greater), chain lightning, control weather, cure moderate wounds (mass), harm, heal, hold person (mass), inflict moderate wounds (mass), insanity, instant summons, phase door, plane shift, power word blind, regenerate, scrying (greater), summon monster VII, symbol of stunning, symbol of weakness, teleport (greater), teleport object, vision, waves of exhaustion"
    ],
    8: ["antipathy, charm monster (mass), clone, cure serious wounds (mass), demand, destruction, discern location, horrid wilting, inflict serious wounds (mass), irresistible dance, maze, mind blank, moment of prescience, power word stun, prying eyes (greater), resurrection, stormbolts*, summon monster VIII, symbol of death, symbol of insanity, sympathy, trap the soul"
    ],
    9: ["astral projection, cure critical wounds (mass), dominate monster, elemental swarm, foresight, hold monster (mass), inflict critical wounds (mass), power word kill, refuge, soul bind, storm of vengeance, suffocation (mass)*, summon monster IX, teleportation circle, wail of the banshee"
    ]
  }
};
