'use strict';

/**
 * @ngdoc function
 * @name pathfinderCharacterBuilderApp.controller:SpellCtrl
 * @description
 * # SpellCtrl
 * Controller of the pathfinderCharacterBuilderApp
 */
angular.module('pathfinderCharacterBuilderApp')
  .controller('SpellCtrl', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
    this.spellsWithDescriptions = spellsWithDescriptions;
    this.spells = spells;
    this.spellsByClass = spellsByClass;
  });

var spellsWithDescriptions = [
  {
    name: "Fireball",
    school: "evocation",
    subschool: null,
    descriptor: "fire",
    spellLevel: "sorcerer/wizard 3, magus 3"
  },
  {
    name: "Cure Light Wounds",
    school: "conjuration",
    subschool: "healing",
    descriptor: null,
    spellLevel: "bard 1, cleric 1, druid 1, paladin 1, ranger 2, witch 1, inquisitor 1, alchemist 1"
  }
];

var spells = [
  "Ablative Barrier",
  "Aboleth's Lung",
  "Absorb Toxicity",
  "Absorbing Inhalation",
  "Absorbing Touch",
  "Abundant Ammunition",
  "Accelerate Poison",
  "Acid Arrow",
  "Acid Fog",
  "Acid Pit",
  "Acid Splash",
  "Acidic Spray",
  "Acute Senses",
  "Adhesive Blood",
  "Adhesive Spittle",
  "Adjuring Step",
  "Adjustable Disguise",
  "Adjustable Polymorph",
  "Adoration",
  "Age Resistance, Greater",
  "Age Resistance, Lesser",
  "Age Resistance",
  "Agressive Thundercloud",
  "Aggressive Thundercloud, Greater",
  "Agonize",
  "Agonizing Rebuke",
  "Aid",
  "Air Bubble",
  "Air Geyser",
  "Air Step",
  "Air Walk, Communal",
  "Air Walk",
  "Alarm",
  "Alchemical Allocation",
  "Alchemical Tinkering",
  "Align Weapon",
  "Align Weapon, Communal",
  "Allegro",
  "Allfood",
  "Alter Self",
  "Alter Musical Instrument",
  "Alter Winds",
  "Amplify Elixir",
  "Analyze Dweomer",
  "Ancestral Regression",
  "Anchored Step",
  "Animal Aspect, Greater",
  "Animal Aspect",
  "Animal Growth",
  "Animal Messenger",
  "Animal Purpose Training",
  "Animal Shapes",
  "Animal Trance",
  "Animate Dead, Lesser",
  "Animate Dead",
  "Animate Objects",
  "Animate Plants",
  "Animate Rope",
  "Anonymous Interaction",
  "Ant Haul",
  "Ant Haul, Communal",
  "Anthropomorphic Animal",
  "Anticipate Peril",
  "Anti-Incorporeal Shell",
  "Antilife Shell",
  "Antimagic Field",
  "Antipathy",
  "Antiplant Shell",
  "Aqueous Orb",
  "Arboreal Hammer",
  "Arcana Theft",
  "Arcane Cannon",
  "Arcane Concordance",
  "Arcane Eye",
  "Arcane Lock",
  "Arcane Mark",
  "Arcane Sight, Greater",
  "Arcane Sight",
  "Archon's Aura",
  "Arrow Eruption",
  "Arrow of Law",
  "Ash Storm",
  "Aspect of the Bear",
  "Aspect of the Falcon",
  "Aspect of the Stag",
  "Aspect of the Wolf",
  "Astral Projection, Lesser",
  "Astral Projection",
  "Atavism, Mass",
  "Atavism",
  "Atonement",
  "Augury",
  "Aura of Doom",
  "Aura of Greater Courage",
  "Aura Sight",
  "Awaken",
  "Badger's Ferocity",
  "Baleful Polymorph",
  "Ball Lightning",
  "Bane",
  "Banish Seeming",
  "Banishment",
  "Banshee Blaste",
  "Bard's Escape",
  "Barkskin",
  "Barrow Haze",
  "Battlemind Link",
  "Battle Trance",
  "Bear's Endurance, Mass",
  "Bear's Endurance",
  "Beast Shape I",
  "Beast Shape II",
  "Beast Shape III",
  "Beast Shape IV",
  "Beastspeak",
  "Beguiling Gift",
  "Bestow Auras",
  "Bestow Curse",
  "Bestow Grace of the Champion",
  "Bestow Grace",
  "Bestow Insight",
  "Bestow Weapon Proficiency",
  "Binding",
  "Binding Earth",
  "Binding Earth, Mass",
  "Black Mark",
  "Black Tentacles",
  "Blade Barrier",
  "Blade Lash",
  "Blade of Bright Victory",
  "Blade of Dark Triumph",
  "Blasphemy",
  "Blaze of Glory",
  "Blazing Rainbow",
  "Bleed",
  "Blend",
  "Bless Water",
  "Bless Weapon",
  "Bless",
  "Blessed Fist",
  "Blessing of Courage and Life",
  "Blessing of Fervor",
  "Blessing of Luck and Resolve",
  "Blessing of Luck and Resolve, Mass",
  "Blessing of the Mole",
  "Blessing of the Salamander",
  "Blight",
  "Blinding Ray",
  "Blindness Deafness",
  "Blink",
  "Blistering Invective",
  "Bloatbomb",
  "Blood Armor",
  "Blood Biography",
  "Blood Blaze",
  "Blood Crow Strike",
  "Blood Mist",
  "Blood Transcription",
  "Blood Scent",
  "Blood Sentinel",
  "Bloodhound",
  "Bloody Claws",
  "Blur",
  "Blurred Movement",
  "Body Capacitance",
  "Boiling Blood",
  "Bomber's Eye",
  "Borrow Fortune",
  "Borrow Skill",
  "Bow Spirit",
  "Bowstaff",
  "Brand, Greater",
  "Brand",
  "Break",
  "Break Enchantment",
  "Breath of Life",
  "Brilliant Inspiration",
  "Bristle",
  "Brow Gasher",
  "Bull's Strength, Mass",
  "Bull's Strength",
  "Bullet Shield",
  "Bullet Ward",
  "Bungle",
  "Buoyancy",
  "Burning Gaze",
  "Burning Hands",
  "Burrow",
  "Burst Bonds",
  "Burst of Nettles",
  "Burst of Speed",
  "Cackling Skull",
  "Cacophonous Call, Mass",
  "Cacophonous Call",
  "Caging Bomb Admixture",
  "Calcific Touch",
  "Call Animal",
  "Call Construct",
  "Call Lightning Storm",
  "Call Lightning",
  "Calm Animals",
  "Calm Emotions",
  "Campfire Wall",
  "Cape of Wasps",
  "Cast Out",
  "Castigate, Mass",
  "Castigate",
  "Cat's Grace, Mass",
  "Cat's Grace",
  "Cause Fear",
  "Caustic Eruption",
  "Certain Grip",
  "Chains of Fire",
  "Chain Lightning",
  "Chain of Perdition",
  "Challenge Evil",
  "Chameleon Stride",
  "Chameleon Stride, Greater",
  "Changestaff",
  "Chaos Hammer",
  "Charm Animal",
  "Charm Monster, Mass",
  "Charm Monster",
  "Charm Person",
  "Chill Metal",
  "Chill Touch",
  "Chord of Shards",
  "Circle of Clarity",
  "Circle of Death",
  "Clairaudience Clairvoyance",
  "Clashing Rocks",
  "Cleanse",
  "Clenched Fist",
  "Climbing Beanstalk",
  "Cloak of Chaos",
  "Cloak of Dreams",
  "Cloak of Shade",
  "Cloak of Winds",
  "Clone",
  "Cloudkill",
  "Cloud Shape",
  "Cold Ice Strike",
  "Color Spray",
  "Command, Greater",
  "Command Plants",
  "Command Undead",
  "Command",
  "Commune with Birds",
  "Commune with Nature",
  "Commune",
  "Companion Life Link",
  "Companion Mind Link",
  "Compassionate Ally",
  "Compel Hostility",
  "Comprehend Languages",
  "Cone of Cold",
  "Confess",
  "Confusion Lesser",
  "Confusion",
  "Conjure Black Pudding",
  "Consecrate",
  "Contact Other Plane",
  "Contagion, Greater",
  "Contagion",
  "Contagious Flame",
  "Contingency",
  "Contingent Action",
  "Contingent Scroll",
  "Continual Flame",
  "Control Construct",
  "Control Plants",
  "Control Summoned Creature",
  "Control Undead",
  "Control Water",
  "Control Weather",
  "Control Winds",
  "Coordinated Effort",
  "Corrosive Consumption",
  "Corrosive Touch",
  "Corruption Resistance",
  "Countless Eyes",
  "Coward's Lament",
  "Crafter's Curse",
  "Crafter's Fortune",
  "Create Demiplane, Greater",
  "Create Demiplane, Lesser",
  "Create Demiplane",
  "Create Food and Water",
  "Create Greater Undead",
  "Create Pit",
  "Create Treasure Map",
  "Create Undead",
  "Create Water",
  "Creeping Doom",
  "Creeping Ice",
  "Crimson Confession",
  "Crushing Despair",
  "Crushing Hand",
  "Cup of Dust",
  "Cure Critical Wounds, Mass",
  "Cure Critical Wounds",
  "Cure Light Wounds, Mass",
  "Cure Light Wounds",
  "Cure Moderate Wounds, Mass",
  "Cure Moderate Wounds",
  "Cure Serious Wounds, Mass",
  "Cure Serious Wounds",
  "Curse of Burning Sleep",
  "Curse of Disgust",
  "Curse of Magic Negation",
  "Curse Water",
  "Curse, Major",
  "Cursed Earth",
  "Cushioning Bands",
  "Damnation Stride",
  "Damp Powder",
  "Dance of A Hundred Cuts",
  "Dance of A Thousand Cuts",
  "Dancing Lantern",
  "Dancing Lights",
  "Darkness",
  "Darkvision, Communal",
  "Darkvision, Greater",
  "Darkvision",
  "Daybreak Arrow",
  "Daylight",
  "Daze Monster",
  "Daze, Mass",
  "Daze",
  "Deadeye's Lore",
  "Deadly Finale",
  "Deadly Juggernaut",
  "Deafening Song Bolt",
  "Death Candle",
  "Death from Below",
  "Death Knell",
  "Death Ward",
  "Deathwatch",
  "Debilitating Portent",
  "Decompose Corpse",
  "Deep Slumber",
  "Deeper Darkness",
  "Defensive Shock",
  "Defile Armor",
  "Deflection",
  "Delay Disease",
  "Delay Pain",
  "Delay Poison, Communal",
  "Delay Poison",
  "Delayed Blast Fireball",
  "Delayed Consumption",
  "Delusional Pride",
  "Demand",
  "Denounce",
  "Desecrate",
  "Destabilize Powder",
  "Destruction",
  "Detect Aberration",
  "Detect Animals or Plants",
  "Detect Chaos",
  "Detect Evil",
  "Detect Good",
  "Detect Law",
  "Detect Magic",
  "Detect Magic",
  "Detect Poison",
  "Detect Scrying",
  "Detect Secret Doors",
  "Detect Snares and Pits",
  "Detect Thoughts",
  "Detect Undead",
  "Detonate",
  "Devolution",
  "Diagnose Disease",
  "Dictum",
  "Dimension Door",
  "Dimensional Anchor",
  "Dimensional Lock",
  "Dimensional",
  "Dimensional Bounce",
  "Diminish Plants",
  "Disable Construct",
  "Discern Lies",
  "Discern Location",
  "Discern Next of Kin",
  "Discordant Blast",
  "Discovery Torch",
  "Disfiguring Touch",
  "Disguise Other",
  "Disguise Self",
  "Disguise Weapon",
  "Disintegrate",
  "Dismissal",
  "Dispel Chaos",
  "Dispel Evil",
  "Dispel Good",
  "Dispel Law",
  "Dispel Magic, Greater",
  "Dispel Magic",
  "Displacement",
  "Disrupt Undead",
  "Disrupting Weapon",
  "Distracting Cacophony",
  "Distressing Tone",
  "Divination",
  "Divine Arrow",
  "Divine Favor",
  "Divine Power",
  "Divine Pursuit",
  "Divine Transfer",
  "Divine Vessel",
  "Dominate Animal",
  "Dominate Monster",
  "Dominate Person",
  "Doom",
  "Draconic Reservoir",
  "Dragon's Breath",
  "Dread Bolt",
  "Dream",
  "Dust Form",
  "Dust of Twilight",
  "Eagle Aerie",
  "Eagle Eye",
  "Eagle's Splendor, Mass",
  "Eagle's Splendor",
  "Ear Piercing Scream",
  "Earth Glide",
  "Earthquake",
  "Echolocation",
  "Effortless Armor",
  "Eldritch Fever",
  "Elemental Aura",
  "Elemental Body I",
  "Elemental Body II",
  "Elemental Body III",
  "Elemental Body IV",
  "Elemental Speech",
  "Elemental Swarm",
  "Elemental Touch",
  "Elude Time",
  "Enchantment Foil",
  "Endure Elements, Communal",
  "Endure Elements",
  "Enemy Hammer",
  "Enemy's Heart",
  "Enemy Insight",
  "Energy Drain",
  "Energy Siege Shot, Greater",
  "Energy Siege Shot",
  "Enervation",
  "Enlarge Person, Mass",
  "Enlarge Person",
  "Entangle",
  "Enter Image",
  "Enthrall",
  "Entropic Shield",
  "Envious Urge",
  "Epidemic",
  "Erase",
  "Eruptive Pustules",
  "Escaping Ward",
  "Ethereal Jaunt",
  "Etherealness",
  "Euphoric Cloud",
  "Euphoric Tranquility",
  "Evolution Surge, Greater",
  "Evolution Surge, Lesser",
  "Evolution Surge",
  "Excruciating Deformation",
  "Expeditious Excavation",
  "Expeditious Retreat",
  "Expend",
  "Explosive Runes",
  "Extreme Flexibility",
  "Exquisite Accompaniment",
  "Eyebite",
  "Eyes of the Void",
  "Fabricate Bullets",
  "Fabricate",
  "Faerie Fire",
  "Fairy Ring Retreat",
  "False Life, Greater",
  "False Life",
  "False Vision",
  "Familiar Double",
  "Familiar Melding",
  "Fear",
  "Fearsome Duplicate",
  "Feast of Ashes",
  "Feast on Fear",
  "Feather Fall",
  "Feather Step, Mass",
  "Feather Step",
  "Feeblemind",
  "Fester, Mass",
  "Fester",
  "Fickle Winds",
  "Fiery Body",
  "Fiery Shuriken",
  "Find Quarry",
  "Find the Path",
  "Find Traps",
  "Finger of Death",
  "Fins to Feet",
  "Fire Breath",
  "Fire of Entanglement",
  "Fire of Judgment",
  "Fire of Vengeance",
  "Fire Seeds",
  "Fire Shield",
  "Fire Snake",
  "Fire Storm",
  "Firestream",
  "Fire Trail",
  "Fire Trap",
  "Fireball",
  "Firebrand",
  "Firefall",
  "Flame Arrow",
  "Flame Blade",
  "Flame Strike",
  "Flames of the Faithful",
  "Flaming Sphere",
  "Flaming Sphere, Greater",
  "Flare Burst",
  "Flare",
  "Flash Fire",
  "Flesh to Stone",
  "Fleshworm Infestation",
  "Flexible Fury",
  "Floating Disk",
  "Fluid Form",
  "Fly, Mass",
  "Fly",
  "Focused Scrutiny",
  "Foe to Friend",
  "Fog Cloud",
  "Follow Aura",
  "Font of Spirit Magic",
  "Fool's Forbiddance",
  "Forbid Action, Greater",
  "Forbid Action",
  "Forbiddance",
  "Force Hook Charge",
  "Force Punch",
  "Forcecage",
  "Forced Quiet",
  "Forced Repentance",
  "Forceful Hand",
  "Forgetful Slumber",
  "Foresight",
  "Forest Friend",
  "Form of the Dragon I",
  "Form of the Dragon II",
  "Form of the Dragon III",
  "Fox's Cunning, Mass",
  "Fox's Cunning",
  "Freedom of Movement",
  "Freedom",
  "Freezing Sphere",
  "Frightful Aspect",
  "Frigid Touch",
  "Frost Fall",
  "Frostbite",
  "Frozen Note",
  "Fumbletongue",
  "Fungal Infestation",
  "Fury of the Sun",
  "Gallant Inspiration",
  "Gaseous Form",
  "Gate",
  "Geas Lesser",
  "Geas Quest",
  "Gentle Breeze",
  "Gentle Repose",
  "Getaway",
  "Geyser",
  "Ghost Sound",
  "Ghostbane Dirge, Mass",
  "Ghostbane Dirge",
  "Ghostly Disguise",
  "Ghoul Touch",
  "Giant Form I",
  "Giant Form II",
  "Giant Vermin",
  "Ghost Wolf",
  "Glibness",
  "Glide",
  "Glitterdust",
  "Globe of Invulnerability Lesser",
  "Globe of Invulnerability",
  "Gloomblind Bolts",
  "Glue Seal",
  "Glyph of Warding, Greater",
  "Glyph of Warding",
  "Good Hope",
  "Goodberry",
  "Grace",
  "Grasping Hand",
  "Gravity Bow",
  "Grease",
  "Greater Command",
  "Grove of Respite",
  "Guards and Wards",
  "Groundswell",
  "Guardian of Faith",
  "Guidance",
  "Guiding Star",
  "Gust of Wind",
  "Gusting Sphere",
  "Half-blood Extraction",
  "Hallow",
  "Hallucinatory Terrain",
  "Halt Undead",
  "Harm",
  "Haste",
  "Haunted Fey Aspect",
  "Haunting Choir",
  "Haunting Mists",
  "Heal, Mass",
  "Heal Mount",
  "Heal",
  "Healing Thief",
  "Healing Warmth",
  "Heart of the Metal",
  "Heat Metal",
  "Heightened Awareness",
  "Heightened Reflexes",
  "Helping Hand",
  "Hellmouth Lash",
  "Hero's Defiance",
  "Heroes Feast",
  "Heroic Finale",
  "Heroic Invocation",
  "Heroism, Greater",
  "Heroism",
  "Hex Glyph",
  "Hex Glyph, Greater",
  "Hex Vulnerability",
  "Hex Ward",
  "Hidden Speech",
  "Hide Campsite",
  "Hide from Animals",
  "Hide from Undead",
  "Hideous Laughter",
  "Hold Animal",
  "Hold Monster, Mass",
  "Hold Monster",
  "Hold Person, Mass",
  "Hold Person",
  "Hold Portal",
  "Holy Aura",
  "Holy Ice",
  "Holy Ice Weapon",
  "Holy Shield",
  "Holy Smite",
  "Holy Sword",
  "Holy Whisper",
  "Holy Word",
  "Honeyed Tongue",
  "Horn of Pursuit",
  "Horrid Wilting",
  "Hostile Juxtaposition, Greater",
  "Hostile Juxtaposition",
  "Hostile Levitation",
  "Howling Agony",
  "Hungry Pit",
  "Hunter's Eye",
  "Hunter's Howl",
  "Hydraulic Push",
  "Hydraulic Torrent",
  "Hypnotic Pattern",
  "Hypnotism",
  "Ice Body",
  "Ice Crystal Teleport",
  "Ice Storm",
  "Icicle Dagger",
  "Icy Prison, Mass",
  "Icy Prison",
  "Identify",
  "Ill Omen",
  "Illusion of Calm",
  "Illusory Script",
  "Illusory Wall",
  "Imbue with Aura",
  "Imbue with Elemental Might",
  "Imbue with Spell Ability",
  "Implosion",
  "Imprisonment",
  "Improve Trap",
  "Incendiary Cloud",
  "Inflict Critical Wounds, Mass",
  "Inflict Critical Wounds",
  "Inflict Light Wounds, Mass",
  "Inflict Light Wounds",
  "Inflict Moderate Wounds, Mass",
  "Inflict Moderate Wounds",
  "Inflict Serious Wounds, Mass",
  "Inflict Serious Wounds",
  "Innocence",
  "Insanity",
  "Insect Plague",
  "Instant Armor",
  "Instant Enemy",
  "Instant Summons",
  "Instrument of Agony",
  "Interplanetary Teleport",
  "Interposing Hand",
  "Interrogation, Greater",
  "Interrogation",
  "Investigate Mind",
  "Invigorate, Mass",
  "Invigorate",
  "Invisibility Alarm",
  "Invisibility, Greater",
  "Invisibility, Mass",
  "Invisibility Purge",
  "Invisibility Sphere",
  "Invisibility",
  "Ironbeard",
  "Iron Body",
  "Ironwood",
  "Irresistible Dance",
  "Jester's Jaunt",
  "Jitterbugs",
  "Jolting Portent",
  "Joyful Rapture",
  "Judgment Light",
  "Jump",
  "Jury Rig",
  "Karmic Blessing",
  "Keen Edge",
  "Keen Senses",
  "Ki Arrow",
  "Ki Leech",
  "Ki Shout",
  "Kinetic Reverberation",
  "King's Castle",
  "Knight's Calling",
  "Knock",
  "Know Direction",
  "Know the Enemy",
  "Languid Bomb Admixture",
  "Lead Blades",
  "Leashed Shackles",
  "Legend Lore",
  "Lend Judgment, Greater",
  "Lend Judgment",
  "Lesser Restoration",
  "Levitate",
  "Liberating Command",
  "Life Bubble",
  "Life Channel",
  "Life Conduit, Greater",
  "Life Conduit, Improved",
  "Life Conduit",
  "Light Lance",
  "Life Pact",
  "Light",
  "Lightning Arc",
  "Lightning Bolt",
  "Lightning Lash Bomb Admixture",
  "Lily Pad Stride",
  "Limited Wish",
  "Linebreaker",
  "Line in the Sand",
  "Litany of Defense",
  "Litany of Eloquence",
  "Litany of Entanglement",
  "Litany of Escape",
  "Litany of Madness",
  "Litany of Righteousness",
  "Litany of Sight",
  "Litany of Sloth",
  "Litany of Thunder",
  "Litany of Vengeance",
  "Litany of Warding",
  "Litany of Weakness",
  "Liveoak",
  "Loathsome Veil",
  "Locate Creature",
  "Locate Object",
  "Locate Weakness",
  "Lock Gaze",
  "Lockjaw",
  "Long Arm",
  "Longshot",
  "Longstrider",
  "Longstrider, Greater",
  "Lullaby",
  "Lunar Veil",
  "Mad Hallucination",
  "Mad Monkeys",
  "Mage Armor",
  "Mage Hand",
  "Mage's Disjunction",
  "Mage's Faithful Hound",
  "Mage's Lucubration",
  "Mage's Magnificent Mansion",
  "Mage's Private Sanctum",
  "Mage's Sword",
  "Magic Aura",
  "Magic Circle Against Chaos",
  "Magic Circle Against Evil",
  "Magic Circle Against Good",
  "Magic Circle Against Law",
  "Magic Fang, Greater",
  "Magic Fang",
  "Magic Jar",
  "Magic Missile",
  "Magic Mouth",
  "Magic Siege Engine, Greater",
  "Magic Siege Engine",
  "Magic Stone",
  "Magic Vestment",
  "Magic Weapon, Greater",
  "Magic Weapon",
  "Magnifying Chime",
  "Major Creation",
  "Major Image",
  "Major Phantom Object",
  "Make Whole",
  "Malfunction",
  "Malicious Spite",
  "Mantle of Calm",
  "Marching Chant",
  "Marid's Mastery",
  "Marionette Possession",
  "Mark of Justice",
  "Mark of Obvious Ethics",
  "Marks of Forbiddance",
  "Mask Dweomer, Communal",
  "Mask Dweomer",
  "Masterwork Transformation",
  "Maze",
  "Meld Into Stone",
  "Memory Lapse",
  "Memorize Page",
  "Mending",
  "Message",
  "Meteor Swarm",
  "Miasmatic Form",
  "Mighty Fist of the Earth",
  "Mind Blank, Communal",
  "Mind Blank",
  "Mind Fog",
  "Mindlocked Messenger",
  "Minor Creation",
  "Minor Dream",
  "Minor Image",
  "Minor Phantom Object",
  "Miracle",
  "Mirage Arcana",
  "Mirror Hideaway",
  "Mirror Image",
  "Mirror Polish",
  "Mirror Strike",
  "Mirror Transport",
  "Misdirection",
  "Miserable Pity",
  "Mislead",
  "Mnemonic Enhancer",
  "Modify Memory",
  "Molten Orb",
  "Moment of Greatness",
  "Moment of Prescience",
  "Monkey Fish",
  "Monstrous Physique I",
  "Monstrous Physique II",
  "Monstrous Physique III",
  "Monstrous Physique IV",
  "Moonstruck",
  "Mount, Communal",
  "Mount",
  "Move Earth",
  "Muffle Sound",
  "Murderous Command",
  "Mutagenic Touch",
  "Named Bullet, Greater",
  "Named Bullet",
  "Nap Stack",
  "Natural Rhythm",
  "Nature's Exile",
  "Nauseating Dart",
  "Nauseating Trail",
  "Negate Aroma",
  "Negative Reaction",
  "Nereid's Grace",
  "Neutralize Poison",
  "Nightmare",
  "Nine Lives",
  "Nixie's Lure",
  "Nondetection, Communal",
  "Nondetection",
  "Oath of Peace",
  "Obscure Object",
  "Obscuring Mist",
  "Obsidian Flow",
  "Old Salt's Curse",
  "Open Close",
  "Oppressive Boredom",
  "Oracle's Burden",
  "Oracle's Vessel",
  "Orb of the Void",
  "Order's Wrath",
  "Overland Flight",
  "Overwhelming Grief",
  "Overwhelming Presence",
  "Owl's Wisdom, Mass",
  "Owl's Wisdom",
  "Pain Strike, Mass",
  "Pain Strike",
  "Paladin's Sacrifice",
  "Paragon Surge",
  "Pass Without Trace",
  "Passwall",
  "Path of Glory",
  "Path of Glory, Greater",
  "Path of the Winds",
  "Peacebond",
  "Pellet Blast",
  "Perceive Cues",
  "Permanency",
  "Permanent Image",
  "Pernicious Poison",
  "Persistent Image",
  "Persistent Vigor",
  "Persuasive Goad",
  "Phantasmal Killer",
  "Phantasmal Revenge",
  "Phantasmal Web",
  "Phantom Blood",
  "Phantom Chariot",
  "Phantom Driver",
  "Phantom Steed, Communal",
  "Phantom Steed",
  "Phantom Trap",
  "Phase Door",
  "Pied Piping",
  "Pierce Disguise",
  "Piercing Shriek",
  "Pilfering Hand",
  "Pillar of Life",
  "Plague Carrier",
  "Plague Storm",
  "Planar Adaptation, Mass",
  "Planar Adaptation",
  "Planar Ally, Greater",
  "Planar Ally Lesser",
  "Planar Ally",
  "Planar Binding, Greater",
  "Planar Binding Lesser",
  "Planar Binding",
  "Plane Shift",
  "Planeslayer's Call",
  "Plant Growth",
  "Plant Shape I",
  "Plant Shape II",
  "Plant Shape III",
  "Play Instrument",
  "Poison",
  "Polar Midnight",
  "Polar Ray",
  "Polymorph Any Object",
  "Polymorph Familiar",
  "Polymorph, Greater",
  "Polymorph",
  "Polypurpose Panacea",
  "Possess Object",
  "Power Word Blind",
  "Power Word Kill",
  "Power Word Stun",
  "Pox Pustules",
  "Prayer",
  "Prediction of Failure",
  "Prehensile Pilfer",
  "Prestidigitation",
  "Primal Scream",
  "Prismatic Sphere",
  "Prismatic Spray",
  "Prismatic Wall",
  "Produce Flame",
  "Programmed Image",
  "Project Image",
  "Protection from Arrows, Communal",
  "Protection from Arrows",
  "Protection from Chaos, Communal",
  "Protection from Chaos",
  "Protection from Energy, Communal",
  "Protection from Energy",
  "Protection from Evil, Communal",
  "Protection from Evil",
  "Protection from Good, Communal",
  "Protection from Good",
  "Protection from Law, Communal",
  "Protection from Law",
  "Protection from Spells",
  "Protective Penumbra",
  "Protective Spirit",
  "Prying Eyes, Greater",
  "Prying Eyes",
  "Pup Shape",
  "Purging Finale",
  "Purified Calling",
  "Purify Food and Drink",
  "Putrefy Food and Drink",
  "Pyrotechnics",
  "Qualm",
  "Quench",
  "Raging Rubble",
  "Rage",
  "Rain of Frogs",
  "Rainbow Pattern",
  "Raise Animal Companion",
  "Raise Dead",
  "Rally Point",
  "Rampart",
  "Rapid Repair",
  "Ray of Enfeeblement",
  "Ray of Exhaustion",
  "Ray of Frost",
  "Ray of Sickening",
  "Read Magic",
  "Rebuke",
  "Recharge Innate Magic",
  "Reckless Infatuation",
  "Recoil Fire",
  "Reduce Animal",
  "Reduce Person, Mass",
  "Reduce Person",
  "Refine Improvised Weapon",
  "Refuge",
  "Regenerate",
  "Reincarnate",
  "Reinforce Armaments, Communal",
  "Reinforce Armaments",
  "Rejuvenate Eidolon, Greater",
  "Rejuvenate Eidolon, Lesser",
  "Rejuvenate Eidolon",
  "Reloading Hands",
  "Remove Blindness Deafness",
  "Remove Curse",
  "Remove Disease",
  "Remove Fear",
  "Remove Paralysis",
  "Remove Sickness",
  "Repair Undead",
  "Repair Undead, Mass",
  "Repel Metal or Stone",
  "Repel Vermin",
  "Repel Wood",
  "Reprobation",
  "Repulsion",
  "Residual Tracking",
  "Resilient Reservoir",
  "Resilient Sphere",
  "Resinous Skin",
  "Resist Energy, Communal",
  "Resist Energy",
  "Resistance",
  "Resonating Word",
  "Resounding Blow",
  "Rest Eternal",
  "Restful Sleep",
  "Restoration, Greater",
  "Restoration Lesser",
  "Restoration",
  "Restore Corpse",
  "Restore Eidolon, Lesser",
  "Restore Eidolon",
  "Resurgent Transformation",
  "Resurrection",
  "Retribution",
  "Returning Weapon, Communal",
  "Returning Weapon",
  "Reverse Gravity",
  "Reviving Finale",
  "Ricochet Shot",
  "Ride the Lightning",
  "Ride the Waves",
  "Righteous Might",
  "Righteous Vigor",
  "River of Wind",
  "River Whip",
  "Rope Trick",
  "Rusting Grasp",
  "Sacred Bond",
  "Sacred Space",
  "Sacrificial Oath",
  "Saddle Surge",
  "Sanctify Armor",
  "Sanctify Corpse",
  "Sanctuary",
  "Sands of Time",
  "Savage Maw",
  "Saving Finale",
  "Scare",
  "Scent Trail",
  "Scintillating Pattern",
  "Scorching Ash Form",
  "Scorching Ray",
  "Scouring Winds",
  "Screech",
  "Screen",
  "Scrying, Greater",
  "Scrying",
  "Sculpt Corpse",
  "Sculpt Simulacrum",
  "Sculpt Sound",
  "Seamantle",
  "Searing Light",
  "Secret Chest",
  "Secret Page",
  "Secure Shelter",
  "See Alignment",
  "See Invisibility",
  "Seek Thoughts",
  "Seeming",
  "Sending",
  "Sense Spirit Magic",
  "Sentry Skull",
  "Sepia Snake Sigil",
  "Sequester",
  "Serenity",
  "Shades",
  "Shadow Bomb Admixture",
  "Shadow Conjuration, Greater",
  "Shadow Conjuration",
  "Shadow Evocation, Greater",
  "Shadow Evocation",
  "Shadow Projection",
  "Shadow Step",
  "Shadow Walk",
  "Shadow Weapon",
  "Shadowbard",
  "Shadow Anchor",
  "Shadowy Haven",
  "Shambler",
  "Shapechange",
  "Shard of Chaos",
  "Share Language",
  "Share Language, Communal",
  "Share Memory",
  "Share Senses",
  "Shared Wrath",
  "Shatter",
  "Shield Companion",
  "Shield of Faith",
  "Shield of Fortification",
  "Shield of Law",
  "Shield Other",
  "Shield",
  "Shifting Sand",
  "Shillelagh",
  "Shock Shield",
  "Shocking Grasp",
  "Shocking Image",
  "Shout, Greater",
  "Shout",
  "Shrink Item",
  "Siege of Trees, Greater",
  "Siege of Trees",
  "Sickening Entanglement",
  "Sickening Strikes",
  "Sift",
  "Silence",
  "Silent Image",
  "Silent Table",
  "Silk to Steel",
  "Silver Darts",
  "Simulacrum, Lesser",
  "Simulacrum",
  "Sirocco",
  "Skinsend",
  "Slay Living",
  "Sleep",
  "Sleepwalk",
  "Sleet Storm",
  "Slipstream",
  "Slow",
  "Slowing Mud",
  "Smug Narcissism",
  "Snake Staff",
  "Snapdragon Fireworks",
  "Snare",
  "Soften Earth and Stone",
  "Solid Fog",
  "Solid Note",
  "Song of Discord",
  "Sonic Form",
  "Sonic Scream",
  "Sonic Thrust",
  "Soothe Construct",
  "Soul Bind",
  "Sound Burst",
  "Sow Thought",
  "Spark",
  "Spawn Ward",
  "Speak with Animals",
  "Speak with Dead",
  "Speak with Haunt",
  "Speak with Plants",
  "Spear of Purity",
  "Spectral Hand",
  "Spellcrash",
  "Spellcrash, Lesser",
  "Spell Immunity, Greater",
  "Spell Immunity, Communal",
  "Spell Immunity, Greater Communal",
  "Spell Immunity",
  "Spell Resistance",
  "Spell Turning",
  "Spellstaff",
  "Spider Climb, Communal",
  "Spider Climb",
  "Spike Growth",
  "Spike Stones",
  "Spiked Pit",
  "Spiritual Ally",
  "Spiritual Weapon",
  "Spit Venom",
  "Spite",
  "Spontaneous Immolation",
  "Squeeze",
  "Stabilize Powder",
  "Stabilize",
  "Statue",
  "Status",
  "Stay the Hand",
  "Steal Breath",
  "Steal Voice",
  "Stench of Prey",
  "Stinking Cloud",
  "Stone Call",
  "Stone Discus",
  "Stone Fist",
  "Stone Shape",
  "Stone Shield",
  "Stone Tell",
  "Stone to Flesh",
  "Stoneskin, Communal",
  "Stoneskin",
  "Storm of Vengeance",
  "Stormbolts",
  "Strangling Hair",
  "Stricken Heart",
  "Strong Jaw",
  "Strong Wings",
  "Stumble Gap",
  "Stunning Barrier",
  "Stunning Barrier, Greater",
  "Stunning Finale",
  "Suffocation, Mass",
  "Suffocation",
  "Suggestion, Mass",
  "Suggestion",
  "Summon Eidolon",
  "Summon Elder Worm",
  "Summon Froghemoth",
  "Summon Instrument",
  "Summon Minor Ally",
  "Summon Minor Monster",
  "Summon Monster I",
  "Summon Monster II",
  "Summon Monster III",
  "Summon Monster IV",
  "Summon Monster IX",
  "Summon Monster Table",
  "Summon Monster V",
  "Summon Monster VI",
  "Summon Monster VII",
  "Summon Monster VIII",
  "Summon Nature's Ally I",
  "Summon Nature's Ally II",
  "Summon Nature's Ally III",
  "Summon Nature's Ally IV",
  "Summon Nature's Ally IX",
  "Summon Nature's Ally V",
  "Summon Nature's Ally VI",
  "Summon Nature's Ally VII",
  "Summon Nature's Ally VIII",
  "Summon Nature's Ally Table",
  "Summon Swarm",
  "Summoner Conduit",
  "Sun Metal",
  "Sunbeam",
  "Sunburst",
  "Sunder Breaker",
  "Sundering Shards",
  "Surmount Affliction",
  "Swarm Skin",
  "Symbol of Death",
  "Symbol of Fear",
  "Symbol of Healing",
  "Symbol of Insanity",
  "Symbol of Laughter",
  "Symbol of Mirroring",
  "Symbol of Pain",
  "Symbol of Persuasion",
  "Symbol of Revelation",
  "Symbol of Scrying",
  "Symbol of Sealing",
  "Symbol of Sleep",
  "Symbol of Slowing",
  "Symbol of Strife",
  "Symbol of Striking",
  "Symbol of Stunning",
  "Symbol of Vulnerability",
  "Symbol of Weakness",
  "Sympathetic Vibration",
  "Sympathy",
  "Tactical Acumen",
  "Tar Ball",
  "Tar Pool",
  "Targeted Bomb Admixture",
  "Telekinesis",
  "Telekinetic Assembly",
  "Telekinetic Charge",
  "Telekinetic Sphere",
  "Telepathic Bond",
  "Teleport, Greater",
  "Teleport Object",
  "Teleport",
  "Teleportation Circle",
  "Temporal Stasis",
  "Temporary Resurrection",
  "Terrain Bond",
  "Terrible Remorse",
  "Theft Ward",
  "Thorn Body",
  "Thorn Javelin",
  "Thorny Entanglement",
  "Threefold Aspect",
  "Thunder Fire",
  "Thundering Drums",
  "Thunderstomp",
  "Thunderstomp, Greater",
  "Time Shudder",
  "Time Stop",
  "Timely Inspiration",
  "Tiny Hut",
  "Tireless Pursuers",
  "Tireless Pursuit",
  "Toilsome Chant",
  "Tongues, Communal",
  "Tongues",
  "Touch Injection",
  "Touch of Combustion",
  "Touch of Fatigue",
  "Touch of Gracelessness",
  "Touch of Idiocy",
  "Touch of Slime",
  "Touch of the Sea",
  "Toxic Gift",
  "Transformation",
  "Transmogrify",
  "Transmute Blood to Acid",
  "Transmute Metal to Wood",
  "Transmute Mud to Rock",
  "Transmute Potion to Poison",
  "Transmute Rock to Mud",
  "Transport Via Plants",
  "Trap the Soul",
  "Treasure Stitching",
  "Tree Shape",
  "Tree Stride",
  "Triggered Suggestion",
  "True Form",
  "True Resurrection",
  "True Seeing",
  "Truespeak",
  "True Strike",
  "Tsunami",
  "Twilight Haze",
  "Twilight Knife",
  "Twin Form",
  "Twisted Space",
  "Unadulterated Loathing",
  "Unbearable Brightness",
  "Unbreakable Construct",
  "Undead Anatomy I",
  "Undead Anatomy II",
  "Undead Anatomy III",
  "Undead Anatomy IV",
  "Undeath to Death",
  "Undine's Curse",
  "Undetectable Alignment",
  "Unerring Weapon",
  "Unfetter",
  "Unhallow",
  "Unholy Aura",
  "Unholy Blight",
  "Unholy Ice",
  "Unholy Ice Weapon",
  "Unholy Sword",
  "Universal Formula",
  "Unliving Rage",
  "Unnatural Lust",
  "Unprepared Combatant",
  "Unseen Servant",
  "Unshakable Chill",
  "Unwilling Shield",
  "Unwitting Ally",
  "Urban Grace",
  "Utter Contempt",
  "Vampiric Shadow Shield",
  "Vampiric Touch",
  "Vanish",
  "Veil of Heaven",
  "Veil of Positive Energy",
  "Veil",
  "Vengeful Outrage",
  "Venomous Bolt",
  "Ventriloquism",
  "Vermin Shape I",
  "Vermin Shape II",
  "Versatile Weapon",
  "Vestment of the Champion",
  "Village Veil",
  "Viper Bomb Admixture",
  "Virtue",
  "Virtuoso Performance",
  "Vision of Hell",
  "Vision",
  "Vitriolic Mist",
  "Vocal Alteration",
  "Volcanic Storm",
  "Vomit Swarm",
  "Vomit Twin",
  "Vortex",
  "Wail of the Banshee",
  "Wake of Light",
  "Walk Through Space",
  "Wall of Blindness/Deafness",
  "Wall of Fire",
  "Wall of Force",
  "Wall of Ice",
  "Wall of Iron",
  "Wall of Lava",
  "Wall of Nausea",
  "Wall of Sound",
  "Wall of Stone",
  "Wall of Suppression",
  "Wall of Thorns",
  "Wandering Star Motes",
  "Ward the Faithful",
  "Ward of the Season",
  "Warding Weapon",
  "Warp Wood",
  "Wartrain Mount",
  "Water Breathing",
  "Water Walk, Communal",
  "Water Walk",
  "Wave Shield",
  "Waves of Ecstasy",
  "Waves of Exhaustion",
  "Waves of Fatigue",
  "Weaken Powder",
  "Weapon of Awe",
  "Web Shelter",
  "Web",
  "Web Bolt",
  "Web Cloud",
  "Weird",
  "Whip of Ants",
  "Whip of Centipedes",
  "Whip of Spiders",
  "Whirlwind",
  "Whispering Lore",
  "Whispering Wind",
  "Widen Auras",
  "Wilderness Soldiers",
  "Wind Walk",
  "Wind Wall",
  "Winds of Vengeance",
  "Wind Blades",
  "Windy Escape",
  "Winter Feathers",
  "Wish",
  "Witness",
  "Wood Shape",
  "Wooden Phalanx",
  "Word of Chaos",
  "Word of Recall",
  "Word of Resolve",
  "World Wave",
  "Wrath",
  "Wrathful Mantle",
  "Wreath of Blades",
  "Youthful Appearance",
  "Zone of Silence",
  "Zone of Truth"
];

var spellsByClass = {
  bard: {
    0: [
    "Dancing Lights: Creates torches or other lights.",
    ],
  },
};
